CREATE TABLE [dbo].[LineTypeSpecifications] (
	[TenantId]						INT,
	[LineType]						NVARCHAR (255),
	[IsActive]						BIT				NOT NULL DEFAULT (1),
	[AppendSql]						NVARCHAR (MAX) SPARSE,
-- For Account, It might be better to use normalized version: Transaction Type, Resource Type, etc, and conclude the IFRS accordingly.
	[Operation1IsVisible]			BIT				NOT NULL DEFAULT(0),
	[Account1IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Custody1IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Resource1IsVisible]			BIT				NOT NULL DEFAULT(0),
	[Amount1IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Value1IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Note1IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Reference1IsVisible]			BIT				NOT NULL DEFAULT(0),
	[RelatedReference1IsVisible]	BIT				NOT NULL DEFAULT(0),
	[RelatedAgent1IsVisible]		BIT				NOT NULL DEFAULT(0),
	[RelatedResource1IsVisible]		BIT				NOT NULL DEFAULT(0),
	[RelatedAmount1IsVisible]		BIT				NOT NULL DEFAULT(0),

	[Operation2IsVisible]			BIT				NOT NULL DEFAULT(0),
	[Account2IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Custody2IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Resource2IsVisible]			BIT				NOT NULL DEFAULT(0),
	[Amount2IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Value2IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Note2IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Reference2IsVisible]			BIT				NOT NULL DEFAULT(0),
	[RelatedReference2IsVisible]	BIT				NOT NULL DEFAULT(0),
	[RelatedAgent2IsVisible]		BIT				NOT NULL DEFAULT(0),
	[RelatedResource2IsVisible]		BIT				NOT NULL DEFAULT(0),
	[RelatedAmount2IsVisible]		BIT				NOT NULL DEFAULT(0),

	[Operation3IsVisible]			BIT				NOT NULL DEFAULT(0),
	[Account3IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Custody3IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Resource3IsVisible]			BIT				NOT NULL DEFAULT(0),
	[Amount3IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Value3IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Note3IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Reference3IsVisible]			BIT				NOT NULL DEFAULT(0),
	[RelatedReference3IsVisible]	BIT				NOT NULL DEFAULT(0),
	[RelatedAgent3IsVisible]		BIT				NOT NULL DEFAULT(0),
	[RelatedResource3IsVisible]		BIT				NOT NULL DEFAULT(0),
	[RelatedAmount3IsVisible]		BIT				NOT NULL DEFAULT(0),

	[Operation4IsVisible]			BIT				NOT NULL DEFAULT(0),
	[Account4IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Custody4IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Resource4IsVisible]			BIT				NOT NULL DEFAULT(0),
	[Amount4IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Value4IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Note4IsVisible]				BIT				NOT NULL DEFAULT(0),
	[Reference4IsVisible]			BIT				NOT NULL DEFAULT(0),
	[RelatedReference4IsVisible]	BIT				NOT NULL DEFAULT(0),
	[RelatedAgent4IsVisible]		BIT				NOT NULL DEFAULT(0),
	[RelatedResource4IsVisible]		BIT				NOT NULL DEFAULT(0),
	[RelatedAmount4IsVisible]		BIT				NOT NULL DEFAULT(0),
-- Entry 1
	[Direction1]					SMALLINT,
	[OperationId1FillSql]			NVARCHAR (MAX) SPARSE,
	[AccountId1FillSql]				NVARCHAR (MAX),
	[CustodyId1FillSql]				NVARCHAR (MAX) SPARSE,
	[ResourceId1FillSql]			NVARCHAR (MAX) SPARSE,
	[Amount1FillSql]				NVARCHAR (MAX) SPARSE,
	[Value1FillSql]					NVARCHAR (MAX) SPARSE,
	[NoteId1FillSql]				NVARCHAR (MAX) SPARSE,
	[Reference1FillSql]				NVARCHAR (MAX) SPARSE,
	[RelatedReference1FillSql]		NVARCHAR (MAX) SPARSE,
	[RelatedAgentId1FillSql]		NVARCHAR (MAX) SPARSE,
	[RelatedResourceId1FillSql]		NVARCHAR (MAX) SPARSE,
	[RelatedAmount1FillSql]			NVARCHAR (MAX) SPARSE,
-- Entry 2
	[Direction2]					SMALLINT,
	[OperationId2FillSql]			NVARCHAR (MAX),
	[AccountId2FillSql]				NVARCHAR (MAX),
	[CustodyId2FillSql]				NVARCHAR (MAX) SPARSE,
	[ResourceId2FillSql]			NVARCHAR (MAX) SPARSE,
	[Amount2FillSql]				NVARCHAR (MAX) SPARSE,
	[Value2FillSql]					NVARCHAR (MAX) SPARSE,
	[NoteId2FillSql]				NVARCHAR (MAX) SPARSE,
	[Reference2FillSql]				NVARCHAR (MAX) SPARSE,
	[RelatedReference2FillSql]		NVARCHAR (MAX) SPARSE,
	[RelatedAgentId2FillSql]		NVARCHAR (MAX) SPARSE,
	[RelatedResourceId2FillSql]		NVARCHAR (MAX) SPARSE,
	[RelatedAmount2FillSql]			NVARCHAR (MAX) SPARSE,
-- Entry 3
	[Direction3]					SMALLINT,
	[OperationId3FillSql]			NVARCHAR (MAX),
	[AccountId3FillSql]				NVARCHAR (MAX),
	[CustodyId3FillSql]				NVARCHAR (MAX) SPARSE,
	[ResourceId3FillSql]			NVARCHAR (MAX) SPARSE,
	[Amount3FillSql]				NVARCHAR (MAX) SPARSE,
	[Value3FillSql]					NVARCHAR (MAX) SPARSE,
	[NoteId3FillSql]				NVARCHAR (MAX) SPARSE,
	[Reference3FillSql]				NVARCHAR (MAX) SPARSE,
	[RelatedReference3FillSql]		NVARCHAR (MAX) SPARSE,
	[RelatedAgentId3FillSql]		NVARCHAR (MAX) SPARSE,
	[RelatedResourceId3FillSql]		NVARCHAR (MAX) SPARSE,
	[RelatedAmount3FillSql]			NVARCHAR (MAX) SPARSE,
-- Entry 4
	[Direction4]					SMALLINT,
	[OperationId4FillSql]			NVARCHAR (MAX),
	[AccountId4FillSql]				NVARCHAR (MAX),
	[CustodyId4FillSql]				NVARCHAR (MAX) SPARSE,
	[ResourceId4FillSql]			NVARCHAR (MAX) SPARSE,
	[Amount4FillSql]				NVARCHAR (MAX) SPARSE,
	[Value4FillSql]					NVARCHAR (MAX) SPARSE,
	[NoteId4FillSql]				NVARCHAR (MAX) SPARSE,
	[Reference4FillSql]				NVARCHAR (MAX) SPARSE,
	[RelatedReference4FillSql]		NVARCHAR (MAX) SPARSE,
	[RelatedAgentId4FillSql]		NVARCHAR (MAX) SPARSE,
	[RelatedResourceId4FillSql]		NVARCHAR (MAX) SPARSE,
	[RelatedAmount4FillSql]			NVARCHAR (MAX) SPARSE,
    CONSTRAINT [PK_LineTypeSpecifications] PRIMARY KEY CLUSTERED ([TenantId] ASC, [LineType] ASC),
	CONSTRAINT [FK_LineTypeSpecifications_LineTypes] FOREIGN KEY ([TenantId], [LineType]) REFERENCES [dbo].[LineTypes] ([TenantId], [Id]) ON DELETE CASCADE ON UPDATE CASCADE
);