CREATE TABLE [dbo].[LineTypeSpecifications] (
	[TenantId]							INT,
	[LineType]							NVARCHAR (255)	NOT NULL,
	[EntryNumber]						TINYINT			NOT NULL,
	[IsActive]							BIT				NOT NULL CONSTRAINT DF_LineTypeSpecifications_IsActive DEFAULT (1),
	[Definition]						NVARCHAR (255)	NOT NULL DEFAULT(N'Calculation'),
	[OperationCalculationBase]			NVARCHAR (255)	DEFAULT(N'Input'),
	[OperationExpression]				NVARCHAR (MAX),
	[AccountCalculationBase]			NVARCHAR (255)	DEFAULT(N'Input'),
	[AccountExpression]					NVARCHAR (MAX),
	[CustodyCalculationBase]			NVARCHAR (255)	DEFAULT(N'Input'),
	[CustodyExpression]					NVARCHAR (MAX),
	[ResourceCalculationBase]			NVARCHAR (255)	DEFAULT(N'Input'),
	[ResourceExpression]				NVARCHAR (MAX),
	[DirectionCalculationBase]			NVARCHAR (255)	DEFAULT(N'Input'),
	[DirectionExpression]				NVARCHAR (MAX),
	[AmountCalculationBase]				NVARCHAR (255)	DEFAULT(N'Input'),
	[AmountExpression]					NVARCHAR (MAX),
	[ValueCalculationBase]				NVARCHAR (255)	DEFAULT(N'Input'),
	[ValueExpression]					NVARCHAR (MAX),
	[NoteCalculationBase]				NVARCHAR (255)	DEFAULT(N'Input'),
	[NoteExpression]					NVARCHAR (MAX),
	[ReferenceCalculationBase]			NVARCHAR (255)	DEFAULT(N'Input'),
	[ReferenceExpression]				NVARCHAR (MAX),
	[RelatedReferenceCalculationBase]	NVARCHAR (255)	DEFAULT(N'Input'),
	[RelatedReferenceExpression]		NVARCHAR (MAX),
	[RelatedAgentCalculationBase]		NVARCHAR (255)	DEFAULT(N'Input'),
	[RelatedAgentExpression]			NVARCHAR (MAX),
	[RelatedResourceCalculationBase]	NVARCHAR (255)	DEFAULT(N'Input'),
	[RelatedResourceExpression]			NVARCHAR (MAX),
	[RelatedAmountCalculationBase]		NVARCHAR (255)	DEFAULT(N'Input'),
	[RelatedAmountExpression]			NVARCHAR (MAX),
	CONSTRAINT [PK_LineTypeSpecifications] PRIMARY KEY CLUSTERED ([TenantId] ASC, [LineType] ASC, [EntryNumber] ASC, [Definition] ASC),
--	CONSTRAINT [FK_LineTypeSpecifications_LineTypes] FOREIGN KEY ([TenantId], [LineType]) REFERENCES [dbo].[LineTypes] ([TenantId], [Id]) ON DELETE CASCADE ON UPDATE CASCADE
);

