CREATE TABLE [dbo].[LineTypeSpecifications] (
	[TenantId]					INT,
	[LineType]					NVARCHAR (255),
	[IsActive]					BIT				NOT NULL CONSTRAINT DF_LineTypeSpecifications_IsActive DEFAULT (1),
	[AppendSQL]					NVARCHAR (MAX) SPARSE,
-- For Account, It might be better to use normalized version: Transaction Type, Resource Type, etc, and conclude the IFRS accordingly.
	[OperationId1Label]			NVARCHAR (255),
	[OperationId1FillSQL]		NVARCHAR (MAX) SPARSE,
	[AccountId1Label]			NVARCHAR (255) SPARSE,
	[AccountId1FillSQL]			NVARCHAR (MAX),
	[CustodyId1Label]			NVARCHAR (255) SPARSE,
	[CustodyId1FillSQL]			NVARCHAR (MAX) SPARSE,
	[ResourceId1Label]			NVARCHAR (255) SPARSE,
	[ResourceId1FillSQL]			NVARCHAR (MAX) SPARSE,
	[Direction1Label]			NVARCHAR (255) SPARSE,
	[Direction1FillSQL]			NVARCHAR (MAX) SPARSE,
	[Amount1Label]				NVARCHAR (255) SPARSE,
	[Amount1FillSQL]			NVARCHAR (MAX) SPARSE,
	[Value1Label]				NVARCHAR (255) SPARSE,
	[Value1FillSQL]				NVARCHAR (MAX) SPARSE,
	[NoteId1Label]				NVARCHAR (255) SPARSE,
	[NoteId1FillSQL]				NVARCHAR (MAX) SPARSE,
	[Reference1Label]			NVARCHAR (255) SPARSE,
	[Reference1FillSQL]			NVARCHAR (MAX) SPARSE,
	[RelatedReference1Label]	NVARCHAR (255) SPARSE,
	[RelatedReference1FillSQL]	NVARCHAR (MAX) SPARSE,
	[RelatedAgentId1Label]		NVARCHAR (255) SPARSE,
	[RelatedAgentId1FillSQL]		NVARCHAR (MAX) SPARSE,
	[RelatedResourceId1Label]		NVARCHAR (255) SPARSE,
	[RelatedResourceId1FillSQL]	NVARCHAR (MAX) SPARSE,
	[RelatedAmount1Label]		NVARCHAR (255) SPARSE,
	[RelatedAmount1FillSQL]		NVARCHAR (MAX) SPARSE,
-- Entry 2
	[Operation2Label]			NVARCHAR (255) SPARSE,
	[Operation2FillSQL]			NVARCHAR (MAX) SPARSE,
	[AccountId2Label]				NVARCHAR (255) SPARSE,
	[AccountId2FillSQL]			NVARCHAR (MAX),
	[CustodyId2Label]				NVARCHAR (255) SPARSE,
	[CustodyId2FillSQL]			NVARCHAR (MAX) SPARSE,
	[ResourceId2Label]			NVARCHAR (255) SPARSE,
	[ResourceId2FillSQL]			NVARCHAR (MAX) SPARSE,
	[Direction2Label]			NVARCHAR (255) SPARSE,
	[Direction2FillSQL]			NVARCHAR (MAX) SPARSE,
	[Amount2Label]				NVARCHAR (255) SPARSE,
	[Amount2FillSQL]			NVARCHAR (MAX) SPARSE,
	[Value2Label]				NVARCHAR (255) SPARSE,
	[Value2FillSQL]				NVARCHAR (MAX) SPARSE,
	[NoteId2Label]				NVARCHAR (255) SPARSE,
	[NoteId2FillSQL]				NVARCHAR (MAX) SPARSE,
	[Reference2Label]			NVARCHAR (255) SPARSE,
	[Reference2FillSQL]			NVARCHAR (MAX) SPARSE,
	[RelatedReference2Label]	NVARCHAR (255) SPARSE,
	[RelatedReference2FillSQL]	NVARCHAR (MAX) SPARSE,
	[RelatedAgentId2Label]		NVARCHAR (255) SPARSE,
	[RelatedAgentId2FillSQL]		NVARCHAR (MAX) SPARSE,
	[RelatedResourceId2Label]		NVARCHAR (255) SPARSE,
	[RelatedResourceId2FillSQL]	NVARCHAR (MAX) SPARSE,
	[RelatedAmount2Label]		NVARCHAR (255) SPARSE,
	[RelatedAmount2FillSQL]		NVARCHAR (MAX) SPARSE,
-- Entry 3
	[Operation3Label]			NVARCHAR (255) SPARSE,
	[Operation3FillSQL]			NVARCHAR (MAX) SPARSE,
	[AccountId3Label]				NVARCHAR (255) SPARSE,
	[AccountId3FillSQL]			NVARCHAR (MAX),
	[CustodyId3Label]				NVARCHAR (255) SPARSE,
	[CustodyId3FillSQL]			NVARCHAR (MAX) SPARSE,
	[ResourceId3Label]			NVARCHAR (255) SPARSE,
	[ResourceId3FillSQL]			NVARCHAR (MAX) SPARSE,
	[Direction3Label]			NVARCHAR (255) SPARSE,
	[Direction3FillSQL]			NVARCHAR (MAX) SPARSE,
	[Amount3Label]				NVARCHAR (255) SPARSE,
	[Amount3FillSQL]			NVARCHAR (MAX) SPARSE,
	[Value3Label]				NVARCHAR (255) SPARSE,
	[Value3FillSQL]				NVARCHAR (MAX) SPARSE,
	[NoteId3Label]				NVARCHAR (255) SPARSE,
	[NoteId3FillSQL]				NVARCHAR (MAX) SPARSE,
	[Reference3Label]			NVARCHAR (255) SPARSE,
	[Reference3FillSQL]			NVARCHAR (MAX) SPARSE,
	[RelatedReference3Label]	NVARCHAR (255) SPARSE,
	[RelatedReference3FillSQL]	NVARCHAR (MAX) SPARSE,
	[RelatedAgentId3Label]		NVARCHAR (255) SPARSE,
	[RelatedAgentId3FillSQL]		NVARCHAR (MAX) SPARSE,
	[RelatedResourceId3Label]		NVARCHAR (255) SPARSE,
	[RelatedResourceId3FillSQL]	NVARCHAR (MAX) SPARSE,
	[RelatedAmount3Label]		NVARCHAR (255) SPARSE,
	[RelatedAmount3FillSQL]		NVARCHAR (MAX) SPARSE,
-- Entry 4
	[Operation4Label]			NVARCHAR (255) SPARSE,
	[Operation4FillSQL]			NVARCHAR (MAX) SPARSE,
	[AccountId4Label]				NVARCHAR (255) SPARSE,
	[AccountId4FillSQL]			NVARCHAR (MAX),
	[CustodyId4Label]				NVARCHAR (255) SPARSE,
	[CustodyId4FillSQL]			NVARCHAR (MAX) SPARSE,
	[ResourceId4Label]			NVARCHAR (255) SPARSE,
	[ResourceId4FillSQL]			NVARCHAR (MAX) SPARSE,
	[Direction4Label]			NVARCHAR (255) SPARSE,
	[Direction4FillSQL]			NVARCHAR (MAX) SPARSE,
	[Amount4Label]				NVARCHAR (255) SPARSE,
	[Amount4FillSQL]			NVARCHAR (MAX) SPARSE,
	[Value4Label]				NVARCHAR (255) SPARSE,
	[Value4FillSQL]				NVARCHAR (MAX) SPARSE,
	[NoteId4Label]				NVARCHAR (255) SPARSE,
	[NoteId4FillSQL]				NVARCHAR (MAX) SPARSE,
	[Reference4Label]			NVARCHAR (255) SPARSE,
	[Reference4FillSQL]			NVARCHAR (MAX) SPARSE,
	[RelatedReference4Label]	NVARCHAR (255) SPARSE,
	[RelatedReference4FillSQL]	NVARCHAR (MAX) SPARSE,
	[RelatedAgentId4Label]		NVARCHAR (255) SPARSE,
	[RelatedAgentId4FillSQL]		NVARCHAR (MAX) SPARSE,
	[RelatedResourceId4Label]		NVARCHAR (255) SPARSE,
	[RelatedResourceId4FillSQL]	NVARCHAR (MAX) SPARSE,
	[RelatedAmount4Label]		NVARCHAR (255) SPARSE,
	[RelatedAmount4FillSQL]		NVARCHAR (MAX) SPARSE,
    CONSTRAINT [PK_LineTypeSpecifications] PRIMARY KEY CLUSTERED ([TenantId] ASC, [LineType] ASC),
--	CONSTRAINT [FK_LineTypeSpecifications_LineTypes] FOREIGN KEY ([TenantId], [LineType]) REFERENCES [dbo].[LineTypes] ([TenantId], [Id]) ON DELETE CASCADE ON UPDATE CASCADE
);