CREATE TABLE [dbo].[RoleMemberships] (
	[Id]				UNIQUEIDENTIFIER	PRIMARY KEY,
	[Userid]			UNIQUEIDENTIFIER	NOT NULL,
	[RoleId]			UNIQUEIDENTIFIER	NOT NULL,
	[Memo]				NVARCHAR (255),
	[CreatedAt]			DATETIMEOFFSET(7)	NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	[CreatedById]		UNIQUEIDENTIFIER	NOT NULL DEFAULT CONVERT(UNIQUEIDENTIFIER, SESSION_CONTEXT(N'UserId')),
	[ModifiedAt]		DATETIMEOFFSET(7)	NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	[ModifiedById]		UNIQUEIDENTIFIER	NOT NULL DEFAULT CONVERT(UNIQUEIDENTIFIER, SESSION_CONTEXT(N'UserId')),
	CONSTRAINT [FK_RoleMemberships__UserId] FOREIGN KEY ([Userid]) REFERENCES [dbo].[LocalUsers] ([Id]),
	CONSTRAINT [FK_RoleMemberships__RoleId] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[Roles] ([Id]),
	CONSTRAINT [FK_RoleMemberships__CreatedById] FOREIGN KEY ([CreatedById]) REFERENCES [dbo].[LocalUsers] ([Id]),
	CONSTRAINT [FK_RoleMemberships__ModifiedById] FOREIGN KEY ([ModifiedById]) REFERENCES [dbo].[LocalUsers] ([Id])
);
GO