CREATE TYPE [dbo].[LineList] AS TABLE (
	[Index]				INT,
	[DocumentIndex]		INT				NOT NULL,
	[Id]				INT,
	[DocumentId]		INT,
	[LineType]			NVARCHAR(255)	NOT NULL,
	[BaseLineId]		INT,
	[ScalingFactor]		FLOAT,
	[Memo]				NVARCHAR (255),
	-- Common for all entries of all lines
	[OperationId]		INT,
	[AccountId]			NVARCHAR (255),
	[CustodyId]			INT,
	[ResourceId]		INT,
	[Direction]			SMALLINT,
	[Amount]			MONEY,
	[Value]				VTYPE,
	[NoteId]			NVARCHAR (255),
	[Reference]			NVARCHAR (255),
	[RelatedReference]	NVARCHAR (255),
	[RelatedAgentId]	INT,
	[RelatedResourceId]	INT,
	[RelatedAmount]		MONEY,
	[EntityState]		NVARCHAR(255)	NOT NULL DEFAULT(N'Inserted'),
	PRIMARY KEY ([Index] ASC),
	CHECK ([EntityState] IN (N'Unchanged', N'Inserted', N'Updated', N'Deleted')),
	CHECK ([EntityState] <> N'Inserted' OR [Id] IS NULL)
);