CREATE TYPE [dbo].[DocumentList] AS TABLE (
	[Index]					INT,
  [Id]					INT,
  [State]					NVARCHAR (255)		NOT NULL,
  [TransactionType]		NVARCHAR (255)		NOT NULL,
	[Mode]					NVARCHAR (255)		NOT NULL DEFAULT(N'Draft'),
  [SerialNumber]			INT,
  [ResponsibleAgentId]	INT,
  [ForwardedToAgentId]	INT,
	[FolderId]				INT,
	[LinesMemo]				NVARCHAR (255),
  [LinesStartDateTime]	DATETIMEOFFSET (7),
  [LinesEndDateTime]		DATETIMEOFFSET (7),
	[LinesCustody1]			INT,
	[LinesCustody2]			INT,
	[LinesCustody3]			INT,
	[LinesReference1]		NVARCHAR(255),
	[LinesReference2]		NVARCHAR(255),
	[LinesReference3]		NVARCHAR(255),
  [CreatedAt]				DATETIMEOFFSET(7)	NOT NULL,
  [CreatedBy]				NVARCHAR(450)		NOT NULL,
  [ModifiedAt]			DATETIMEOFFSET(7)	NOT NULL, 
  [ModifiedBy]			NVARCHAR(450)		NOT NULL,
	[EntityState]			NVARCHAR(255)		NOT NULL DEFAULT(N'Inserted'),
  PRIMARY KEY CLUSTERED ([Index] ASC),
	CHECK ([State]	IN (N'Plan', N'Inquiry', N'Template', N'Demand', N'Voucher')),
	CHECK ([Mode]	IN (N'Void', N'Draft', N'Submitted', N'Posted')),
	CHECK ([EntityState] IN (N'Unchanged', N'Inserted', N'Updated', N'Deleted')),
	CHECK ([EntityState] <> N'Inserted' OR [Id] IS NULL)
	);