CREATE TYPE [dbo].[DocumentLineTypeList] AS TABLE (
	[DocumentIndex]		INT,
	[LineType]			NVARCHAR (255),
	[BaseLineId]		INT,
	[ScalingFactor]		FLOAT,
	[Memo]				NVARCHAR(255),
	[OperationId]		INT	,
	[AccountId]			NVARCHAR (255),
	[CustodyId]			INT,
	[ResourceId]		INT	,
	[Direction]			SMALLINT,
	[Amount]			MONEY,
	[Value]				VTYPE,
	[NoteId]			NVARCHAR (255),
	[Reference]			NVARCHAR (255),
	[RelatedReference]	NVARCHAR (255),
	[RelatedAgentId]	INT,
	[RelatedResourceId]	INT,
	[RelatedAmount]		MONEY,
	[EntityState]		NVARCHAR(255)		NOT NULL DEFAULT(N'Inserted'),
	PRIMARY KEY ([DocumentIndex] ASC, [LineType] ASC),
	CHECK ([EntityState] IN (N'Unchanged', N'Inserted', N'Updated', N'Deleted'))
);
