CREATE TYPE [dbo].[AgentList] AS TABLE (
	[Index]						INT				IDENTITY(0, 1),
	[Id]						INT,
	[AgentType]					NVARCHAR (255)	NOT NULL,
	[Name]						NVARCHAR (255)	NOT NULL,
	[Name2]						NVARCHAR (255),
	[Code]						NVARCHAR (255),
	[Address]					NVARCHAR (1024),
	[BirthDateTime]				DATETIMEOFFSET (7),
	[IsRelated]					BIT				NOT NULL DEFAULT (0),
	[TaxIdentificationNumber]	NVARCHAR (255),
	[Title]						NVARCHAR (255),
	[Gender]					NCHAR (1),
	[EntityState]				NVARCHAR(255)	NOT NULL DEFAULT(N'Inserted'),
	PRIMARY KEY ([Index] ASC),
	INDEX IX_AgentList__Code ([Code]),
	CHECK ([AgentType] IN (N'Individual', N'Organization', N'Position')),
	CHECK ([EntityState] IN (N'Unchanged', N'Inserted', N'Updated', N'Deleted')),
	CHECK ([EntityState] <> N'Inserted' OR [Id] IS NULL)
);