CREATE TYPE [dbo].[EntryList] AS TABLE (
	[Id]				INT,
	[LineId]			INT					NOT NULL,
	[EntryNumber]		INT					NOT NULL,
	[OperationId]		INT,
	[Reference]			NVARCHAR (255),
	[AccountId]			NVARCHAR (255),
	[CustodyId]			INT,
	[ResourceId]		INT,
	[Direction]			SMALLINT,
	[Amount]			MONEY,
	[Value]				DECIMAL(38,10),
	[NoteId]			NVARCHAR (255),
	[RelatedReference]	NVARCHAR (255),
	[RelatedAgentId]	INT,
	[RelatedResourceId]	INT,
	[RelatedAmount]		MONEY,
	[CreatedAt]			DATETIMEOFFSET(7)	NOT NULL,
	[CreatedBy]			NVARCHAR(450)		NOT NULL,
	[ModifiedAt]		DATETIMEOFFSET(7)	NOT NULL, 
	[ModifiedBy]		NVARCHAR(450)		NOT NULL,
	[EntityState]		NVARCHAR(255)		NOT NULL DEFAULT(N'Inserted'),
	PRIMARY KEY CLUSTERED ([Id] ASC),
	CHECK ([Direction] IN (-1, 1)),
	CHECK ([EntityState] IN (N'Unchanged', N'Inserted', N'Updated', N'Deleted'))
);
