CREATE TABLE #Accounts (
    [Id]              NVARCHAR (255)  NOT NULL,
    [Name]            NVARCHAR (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [Code]            NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [IsActive]        BIT             NOT NULL,
    [ParentId]        NVARCHAR (255)  NULL,
    [AccountType]     NVARCHAR (10)   CONSTRAINT [DF_Accounts_AccountType] DEFAULT (N'Custom') NOT NULL,
    [AccountSpecification] NVARCHAR (50)   CONSTRAINT [DF_Accounts_AccountSpecification] DEFAULT (N'Basic') NOT NULL,
    [IsExtensible]    BIT             CONSTRAINT [DF_Accounts_IsExtensible] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_Accounts_1] PRIMARY KEY NONCLUSTERED ([Id] ASC)
);
INSERT INTO #Accounts(AccountType, IsActive, Code, Id, [Name]) VALUES
('Regulatory', 1, '1', 'Assets', 'Assets')
,('Regulatory', 1, '11', 'NoncurrentAssets', 'Non-current assets')
,('Regulatory', 1, '1101', 'PropertyPlantAndEquipment', 'Property, plant and equipment')
,('Regulatory', 1, '110101', 'LandAndBuildings', 'Land and buildings')
,('Regulatory', 1, '1101011', 'Land', 'Land')
,('Regulatory', 1, '1101012', 'Buildings', 'Buildings')
,('Regulatory', 1, '110102', 'Machinery', 'Machinery')
,('Regulatory', 1, '110103', 'Vehicles', 'Vehicles')
,('Regulatory', 0, '1101031', 'Ships', 'Ships')
,('Regulatory', 0, '1101032', 'Aircraft', 'Aircraft')
,('Regulatory', 1, '1101033', 'MotorVehicles', 'Motor vehicles')
,('Regulatory', 1, '110104', 'FixturesAndFittings', 'Fixtures and fittings')
,('Regulatory', 1, '110105', 'OfficeEquipment', 'Office equipment')
,('Correction', 1, '110106', 'ComputerEquipment', 'Computer equipment')
,('Correction', 1, '110107', 'CommunicationAndNetworkEquipment', 'Communication and network equipment')
,('Correction', 1, '110108', 'NetworkInfrastructure', 'Network infrastructure')
,('Regulatory', 0, '110109', 'BearerPlants', 'Bearer plants')
,('Regulatory', 0, '110110', 'TangibleExplorationAndEvaluationAssets', 'Tangible exploration and evaluation assets')
,('Regulatory', 0, '110111', 'MiningAssets', 'Mining assets')
,('Correction', 0, '1101111', 'MiningProperty', 'Mining property')
,('Regulatory', 0, '110112', 'OilAndGasAssets', 'Oil and gas assets')
,('Correction', 1, '110113', 'PowerGeneratingAssets', 'Power generating assets')
,('Correction', 1, '110114', 'LeaseholdImprovements', 'Leasehold improvements')
,('Regulatory', 1, '110115', 'ConstructionInProgress', 'Construction in progress')
,('Regulatory', 1, '110116', 'OtherPropertyPlantAndEquipment', 'Other property, plant and equipment')
,('Extension', 1, '1101161', 'SparePartsInventory', 'Spare parts inventory')
,('Extension', 1, '1101162', 'RepairsAndMaintenanceAllowance', 'Repairs and maintenance allowance')
,('Regulatory', 1, '1102', 'InvestmentProperty', 'Investment property')
,('Regulatory', 1, '11021', 'InvestmentPropertyCompleted', 'Investment property completed')
,('Regulatory', 1, '11022', 'InvestmentPropertyUnderConstructionOrDevelopment', 'Investment property under construction or development')
,('Regulatory', 1, '1103', 'Goodwill', 'Goodwill')
,('Regulatory', 1, '1104', 'IntangibleAssetsOtherThanGoodwill', 'Intangible assets other than goodwill')
,('Regulatory', 1, '110401', 'BrandNames', 'Brand names')
,('Regulatory', 0, '110402', 'IntangibleExplorationAndEvaluationAssets', 'Intangible exploration and evaluation assets')
,('Regulatory', 0, '110403', 'MastheadsAndPublishingTitles', 'Mastheads and publishing titles')
,('Regulatory', 1, '110404', 'ComputerSoftware', 'Computer software')
,('Regulatory', 0, '110405', 'LicencesAndFranchises', 'Licences and franchises')
,('Regulatory', 0, '1104051', 'Licences', 'Licences')
,('Regulatory', 0, '1104052', 'Franchises', 'Franchises')
,('Regulatory', 0, '110406', 'CopyrightsPatentsAndOtherIndustrialPropertyRightsServiceAndOperatingRights', 'Copyrights, patents and other industrial property rights, service and operating rights')
,('Regulatory', 0, '1104061', 'AirportLandingRightsMember', 'Airport landing rights [member]')
,('Regulatory', 0, '1104062', 'MiningRightsMember', 'Mining rights [member]')
,('Regulatory', 0, '1104063', 'BroadcastingRightsMember', 'Broadcasting rights [member]')
,('Regulatory', 0, '1104064', 'ServiceConcessionRightsMember', 'Service concession rights [member]')
,('Regulatory', 1, '110407', 'RecipesFormulaeModelsDesignsAndPrototypes', 'Recipes, formulae, models, designs and prototypes')
,('Correction', 1, '110408', 'CustomerRelatedIntangibleAssets', 'Customer related intangible assets')
,('Correction', 1, '110409', 'ValueOfBusinessAcquired', 'Value of business acquired')
,('Correction', 1, '110410', 'CapitalisedDevelopmentExpenditure', 'Capitalized development expenditure')
,('Regulatory', 1, '110411', 'IntangibleAssetsUnderDevelopment', 'Intangible assets under development')
,('Correction', 1, '110412', 'TechnologybasedIntangibleAssets', 'Technology based intangible assets')
,('Regulatory', 1, '110413', 'OtherIntangibleAssets', 'Other intangible assets')
,('Regulatory', 1, '1105', 'InvestmentAccountedForUsingEquityMethod', 'Investments accounted for using equity method')
,('Regulatory', 1, '11051', 'InvestmentsInJointVenturesAccountedForUsingEquityMethod', 'Investments in joint ventures accounted for using equity method')
,('Regulatory', 1, '11052', 'InvestmentsInAssociatesAccountedForUsingEquityMethod', 'Investments in associates accounted for using equity method')
,('Regulatory', 1, '1106', 'InvestmentsInSubsidiariesJointVenturesAndAssociates', 'Investments in subsidiaries, joint ventures and associates')
,('Regulatory', 1, '11061', 'InvestmentsInSubsidiaries', 'Investments in subsidiaries')
,('Regulatory', 1, '11062', 'InvestmentsInJointVentures', 'Investments in joint ventures')
,('Regulatory', 1, '11063', 'InvestmentsInAssociates', 'Investments in associates')
,('Regulatory', 0, '1107', 'NoncurrentBiologicalAssets', 'Non-current biological assets')
,('Regulatory', 1, '1108', 'NoncurrentReceivables', 'Trade and other non-current receivables')
,('Regulatory', 1, '11081', 'NoncurrentTradeReceivables', 'Non-current trade receivables')
,('Regulatory', 1, '11082', 'NoncurrentReceivablesDueFromRelatedParties', 'Non-current receivables due from related parties')
,('Regulatory', 1, '110821', 'NoncurrentReceivablesDueFromAssociates', 'Non-current receivables due from associates')
,('Regulatory', 1, '110822', 'NoncurrentReceivablesDueFromJointVentures', 'Non-current receivables due from joint ventures')
,('Regulatory', 1, '11083', 'NoncurrentPrepaymentsAndNoncurrentAccruedIncome', 'Non-current prepayments and non-current accrued income')
,('Regulatory', 1, '110831', 'NoncurrentPrepayments', 'Non-current prepayments')
,('Regulatory', 1, '1108311', 'NoncurrentLeasePrepayments', 'Non-current lease prepayments')
,('Extension', 1, '11083111', 'NoncurrentLeasePrepaymentsCostOfSales', 'Non-current lease prepayments - Cost of sales')
,('Extension', 1, '11083112', 'NoncurrentLeasePrepaymentsDistributionCosts', 'Non-current lease prepayments - Distrbution costs')
,('Extension', 1, '11083113', 'NoncurrentLeasePrepaymentsAdministrativeExpenses', 'Non-current lease prepayments - Administrative expenses')
,('Regulatory', 1, '110832', 'NoncurrentAccruedIncome', 'Non-current accrued income')
,('Regulatory', 1, '11084', 'NoncurrentReceivablesFromTaxesOtherThanIncomeTax', 'Non-current receivables from taxes other than income tax')
,('Regulatory', 1, '110841', 'NoncurrentValueAddedTaxReceivables', 'Non-current value added tax receivables')
,('Regulatory', 1, '11085', 'NoncurrentReceivablesFromSaleOfProperties', 'Non-current receivables from sale of properties')
,('Regulatory', 1, '11086', 'NoncurrentReceivablesFromRentalOfProperties', 'Non-current receivables from rental of properties')
,('Regulatory', 1, '11087', 'OtherNoncurrentReceivables', 'Other non-current receivables')
,('Regulatory', 1, '1109', 'NoncurrentInventories', 'Non-current inventories')
,('Regulatory', 0, '11091', 'NoncurrentOreStockpiles', 'Non-current ore stockpiles')
,('Regulatory', 1, '1110', 'DeferredTaxAssets', 'Deferred tax assets')
,('Regulatory', 1, '1111', 'CurrentTaxAssetsNoncurrent', 'Current tax assets, non-current')
,('Regulatory', 1, '1112', 'OtherNoncurrentFinancialAssets', 'Other non-current financial assets')
,('Regulatory', 1, '11121', 'NoncurrentFinancialAssetsAtFairValueThroughProfitOrLoss', 'Non-current financial assets at fair value through profit or loss')
,('Regulatory', 1, '111211', 'NoncurrentFinancialAssetsAtFairValueThroughProfitOrLossDesignatedUponInitialRecognition', 'Non-current financial assets at fair value through profit or loss, designated upon initial recognition or subsequently')
,('Regulatory', 1, '111212', 'NoncurrentFinancialAssetsAtFairValueThroughProfitOrLossClassifiedAsHeldForTrading', 'Non-current financial assets at fair value through profit or loss, classified as held for trading')
,('Regulatory', 1, '111213', 'NoncurrentFinancialAssetsAtFairValueThroughProfitOrLossMandatorilyMeasuredAtFairValue', 'Non-current financial assets at fair value through profit or loss, mandatorily measured at fair value')
,('Regulatory', 1, '11122', 'NoncurrentFinancialAssetsAtFairValueThroughOtherComprehensiveIncome', 'Non-current financial assets at fair value through other comprehensive income')
,('Regulatory', 1, '111221', 'NoncurrentFinancialAssetsMeasuredAtFairValueThroughOtherComprehensiveIncome', 'Non-current financial assets measured at fair value through other comprehensive income')
,('Regulatory', 1, '111222', 'NoncurrentInvestmentsInEquityInstrumentsDesignatedAtFairValueThroughOtherComprehensiveIncome', 'Non-current investments in equity instruments designated at fair value through other comprehensive income')
,('Regulatory', 1, '11123', 'NoncurrentFinancialAssetsAtAmortisedCost', 'Non-current financial assets at amortised cost')
,('Regulatory', 1, '1113', 'OtherNoncurrentNonfinancialAssets', 'Other non-current non-financial assets')
,('Regulatory', 1, '1114', 'NoncurrentNoncashAssetsPledgedAsCollateralForWhichTransfereeHasRightByContractOrCustomToSellOrRepledgeCollateral', 'Non-current non-cash assets pledged as collateral for which transferee has right by contract or custom to sell or repledge collateral')
,('Regulatory', 1, '12', 'CurrentAssets', 'Current assets')
,('Regulatory', 1, '121', 'CurrentAssetsOtherThanAssetsOrDisposalGroupsClassifiedAsHeldForSaleOrAsHeldForDistributionToOwners', 'Current assets other than non-current assets or disposal groups classified as held for sale or as held for distribution to owners')
,('Regulatory', 1, '1211', 'Inventories', 'Current inventories')
,('Regulatory', 1, '121101', 'CurrentRawMaterialsAndCurrentProductionSupplies', 'Current raw materials and current production supplies')
,('Regulatory', 1, '1211011', 'RawMaterials', 'Current raw materials')
,('Regulatory', 1, '1211012', 'ProductionSupplies', 'Current production supplies')
,('Regulatory', 1, '121102', 'Merchandise', 'Current merchandise')
,('Regulatory', 1, '121103', 'CurrentFoodAndBeverage', 'Current food and beverage')
,('Regulatory', 0, '121104', 'CurrentAgriculturalProduce', 'Current agricultural produce')
,('Regulatory', 1, '121105', 'WorkInProgress', 'Current work in progress')
,('Regulatory', 1, '121106', 'FinishedGoods', 'Current finished goods')
,('Regulatory', 1, '121107', 'CurrentPackagingAndStorageMaterials', 'Current packaging and storage materials')
,('Regulatory', 1, '121108', 'SpareParts', 'Current spare parts')
,('Regulatory', 1, '121109', 'CurrentFuel', 'Current fuel')
,('Regulatory', 1, '121110', 'PropertyIntendedForSaleInOrdinaryCourseOfBusiness', 'Property intended for sale in ordinary course of business')
,('Regulatory', 1, '121111', 'CurrentInventoriesInTransit', 'Current inventories in transit')
,('Regulatory', 1, '121112', 'OtherInventories', 'Other current inventories')
,('Regulatory', 1, '1212', 'TradeAndOtherCurrentReceivables', 'Trade and other current receivables')
,('Regulatory', 1, '12121', 'CurrentTradeReceivables', 'Current trade receivables')
,('Extension', 1, '121211', 'CurrentReceivablesFromTradeCustomers', 'Current trade customers receivables')
,('Extension', 1, '121212', 'CurrentReceivablesFromLessees', 'Current lessees receivables')
,('Regulatory', 1, '12122', 'TradeAndOtherCurrentReceivablesDueFromRelatedParties', 'Current receivables due from related parties')
,('Extension', 1, '121221', 'CurrentReceivablesDueFromRelatedTradeCustomers', 'Current receivables due from related trade customers')
,('Extension', 1, '121222', 'CurrentReceivablesDueFromRelatedLessees', 'Current receivables due from related lessees')
,('Regulatory', 0, '121223', 'CurrentReceivablesDueFromAssociates', 'Current receivables due from associates')
,('Regulatory', 0, '121224', 'CurrentReceivablesDueFromJointVentures', 'Current receivables due from joint ventures')
,('Regulatory', 1, '12123', 'CurrentPrepaymentsAndCurrentAccruedIncome', 'Current prepayments and current accrued income')
,('Regulatory', 1, '121231', 'CurrentPrepayments', 'Current prepayments')
,('Regulatory', 1, '1212311', 'CurrentAdvancesToSuppliers', 'Current advances to suppliers')
,('Regulatory', 1, '1212312', 'CurrentPrepaidExpenses', 'Current prepaid expenses')
,('Regulatory', 1, '121232', 'CurrentAccruedIncome', 'Current accrued income')
,('Extension', 1, '1212321', 'GoodsAndServicesDeliveredToCustomerButNotBilled', 'Goods and services delivered to customer but not billed')
,('Extension', 1, '1212322', 'RentAccruedIncome', 'Rent accrued income')
,('Regulatory', 1, '12124', 'CurrentReceivablesFromTaxesOtherThanIncomeTax', 'Current receivables from taxes other than income tax')
,('Regulatory', 1, '121241', 'CurrentValueAddedTaxReceivables', 'Current value added tax receivables')
,('Regulatory', 1, '12125', 'CurrentReceivablesFromSaleOfProperties', 'Current receivables from sale of properties')
,('Regulatory', 1, '12126', 'CurrentReceivablesFromRentalOfProperties', 'Current receivables from rental of properties')
,('Regulatory', 1, '12127', 'OtherCurrentReceivables', 'Other current receivables')
,('Extension', 1, '121271', 'GoodsAndServicesBilledBySupplierButNotReceived', 'Goods and services billed by supplier but not received')
,('Extension', 1, '121272', 'LeaseInBilledByLessorButNotReceived', 'Lease in billed by lessor but not received')
,('Regulatory', 1, '1213', 'CurrentTaxAssetsCurrent', 'Current tax assets, current')
,('Extension', 1, '12131', 'CurrentWithholdingTaxReceivables', 'Current withholding tax receivables')
,('Regulatory', 1, '1214', 'CurrentBiologicalAssets', 'Current biological assets')
,('Regulatory', 1, '1215', 'OtherCurrentFinancialAssets', 'Other current financial assets')
,('Regulatory', 1, '12151', 'CurrentFinancialAssetsAtFairValueThroughProfitOrLoss', 'Current financial assets at fair value through profit or loss')
,('Regulatory', 1, '121511', 'CurrentFinancialAssetsAtFairValueThroughProfitOrLossDesignatedUponInitialRecognition', 'Current financial assets at fair value through profit or loss, designated upon initial recognition or subsequently')
,('Regulatory', 1, '121512', 'CurrentFinancialAssetsAtFairValueThroughProfitOrLossClassifiedAsHeldForTrading', 'Current financial assets at fair value through profit or loss, classified as held for trading')
,('Regulatory', 1, '121513', 'CurrentFinancialAssetsAtFairValueThroughProfitOrLossMandatorilyMeasuredAtFairValue', 'Current financial assets at fair value through profit or loss, mandatorily measured at fair value')
,('Regulatory', 1, '12152', 'CurrentFinancialAssetsAtFairValueThroughOtherComprehensiveIncome', 'Current financial assets at fair value through other comprehensive income')
,('Regulatory', 1, '121521', 'CurrentFinancialAssetsMeasuredAtFairValueThroughOtherComprehensiveIncome', 'Current financial assets measured at fair value through other comprehensive income')
,('Regulatory', 1, '121522', 'CurrentInvestmentsInEquityInstrumentsDesignatedAtFairValueThroughOtherComprehensiveIncome', 'Current investments in equity instruments designated at fair value through other comprehensive income')
,('Regulatory', 1, '12153', 'CurrentFinancialAssetsAtAmortisedCost', 'Current financial assets at amortised cost')
,('Regulatory', 1, '1216', 'OtherCurrentNonfinancialAssets', 'Other current non-financial assets')
,('Regulatory', 1, '1217', 'CashAndCashEquivalents', 'Cash and cash equivalents')
,('Regulatory', 1, '12171', 'Cash', 'Cash')
,('Regulatory', 1, '121711', 'CashOnHand', 'Cash on hand')
,('Regulatory', 1, '121712', 'BalancesWithBanks', 'Balances with banks')
,('Regulatory', 1, '12172', 'CashEquivalents', 'Cash equivalents')
,('Regulatory', 1, '121721', 'ShorttermDepositsClassifiedAsCashEquivalents', 'Short-term deposits, classified as cash equivalents')
,('Regulatory', 1, '121722', 'ShorttermInvestmentsClassifiedAsCashEquivalents', 'Short-term investments, classified as cash equivalents')
,('Regulatory', 1, '121723', 'BankingArrangementsClassifiedAsCashEquivalents', 'Other banking arrangements, classified as cash equivalents')
,('Regulatory', 1, '12173', 'OtherCashAndCashEquivalents', 'Other cash and cash equivalents')
,('Extension', 1, '121731', 'PaymentIssues', 'Payment orders')
,('Extension', 1, '121732', 'PaymentReceipts', 'Receipt orders')
,('Regulatory', 1, '1218', 'CurrentNoncashAssetsPledgedAsCollateralForWhichTransfereeHasRightByContractOrCustomToSellOrRepledgeCollateral', 'Current non-cash assets pledged as collateral for which transferee has right by contract or custom to sell or repledge collateral')
,('Regulatory', 1, '13', 'NoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForSaleOrAsHeldForDistributionToOwners', 'Non-current assets or disposal groups classified as held for sale or as held for distribution to owners')
,('Regulatory', 1, '131', 'NoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForDistributionToOwners', 'Non-current assets or disposal groups classified as held for distribution to owners')
,('Regulatory', 1, '132', 'NoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForSale', 'Non-current assets or disposal groups classified as held for sale')

,('Regulatory', 1, '2', 'Equity', 'Equity')
,('Regulatory', 1, '21', 'IssuedCapital', 'Issued capital')
,('Regulatory', 1, '22', 'SharePremium', 'Share premium')
,('Regulatory', 0, '23', 'TreasuryShares', 'Treasury shares')
,('Regulatory', 1, '24', 'OtherEquityInterest', 'Other equity interest')
,('Regulatory', 1, '25', 'OtherReserves', 'Other reserves')
,('Regulatory', 1, '2501', 'RevaluationSurplus', 'Revaluation surplus')
,('Regulatory', 1, '2502', 'ReserveOfExchangeDifferencesOnTranslation', 'Reserve of exchange differences on translation')
,('Regulatory', 0, '2503', 'ReserveOfCashFlowHedges', 'Reserve of cash flow hedges')
,('Regulatory', 0, '2504', 'ReserveOfGainsAndLossesOnHedgingInstrumentsThatHedgeInvestmentsInEquityInstruments', 'Reserve of gains and losses on hedging instruments that hedge investments in equity instruments')
,('Regulatory', 0, '2505', 'ReserveOfChangeInValueOfTimeValueOfOptions', 'Reserve of change in value of time value of options')
,('Regulatory', 0, '2506', 'ReserveOfChangeInValueOfForwardElementsOfForwardContracts', 'Reserve of change in value of forward elements of forward contracts')
,('Regulatory', 1, '2507', 'ReserveOfChangeInValueOfForeignCurrencyBasisSpreads', 'Reserve of change in value of foreign currency basis spreads')
,('Regulatory', 1, '2508', 'ReserveOfGainsAndLossesOnFinancialAssetsMeasuredAtFairValueThroughOtherComprehensiveIncome', 'Reserve of gains and losses on financial assets measured at fair value through other comprehensive income')
,('Regulatory', 0, '2509', 'ReserveOfSharebasedPayments', 'Reserve of share-based payments')
,('Regulatory', 1, '2510', 'ReserveOfRemeasurementsOfDefinedBenefitPlans', 'Reserve of remeasurements of defined benefit plans')
,('Regulatory', 1, '2511', 'AmountRecognisedInOtherComprehensiveIncomeAndAccumulatedInEquityRelatingToNoncurrentAssetsOrDisposalGroupsHeldForSale', 'Amount recognised in other comprehensive income and accumulated in equity relating to non-current assets or disposal groups held for sale')
,('Regulatory', 1, '2512', 'ReserveOfGainsAndLossesFromInvestmentsInEquityInstruments', 'Reserve of gains and losses from investments in equity instruments')
,('Regulatory', 1, '2513', 'ReserveOfChangeInFairValueOfFinancialLiabilityAttributableToChangeInCreditRiskOfLiability', 'Reserve of change in fair value of financial liability attributable to change in credit risk of liability')
,('Regulatory', 1, '2514', 'ReserveForCatastrophe', 'Reserve for catastrophe')
,('Regulatory', 1, '2515', 'ReserveForEqualisation', 'Reserve for equalisation')
,('Regulatory', 1, '2516', 'ReserveOfDiscretionaryParticipationFeatures', 'Reserve of discretionary participation features')
,('Regulatory', 1, '2517', 'StatutoryReserve', 'Statutory reserve')
,('Regulatory', 1, '2518', 'CapitalRedemptionReserve', 'Capital redemption reserve')
,('Regulatory', 1, '2519', 'MergerReserve', 'Merger reserve')
,('Regulatory', 1, '2520', 'ReserveOfEquityComponentOfConvertibleInstruments', 'Reserve of equity component of convertible instruments')
,('Correction', 1, '2521', 'AccumulatedOtherComprehensiveIncome', 'Accumulated other comprehensive income')
,('Correction', 1, '2522', 'CapitalReserve', 'Capital reserve')
,('Correction', 1, '2523', 'AdditionalPaidinCapital', 'Additional paid-in capital')
,('Correction', 1, '2524', 'MiscellaneousOtherReserves', 'Miscellaneous other reserves')
,('Regulatory', 1, '26', 'RetainedEarnings', 'Retained earnings')
,('Extension', 1, '29', 'BalancesMigration', 'Balances Migration')

,('Regulatory', 1, '3', 'Liabilities', 'Liabilities')
,('Regulatory', 1, '31', 'NoncurrentLiabilities', 'Non-current liabilities')
,('Regulatory', 1, '311', 'NoncurrentProvisions', 'Non-current provisions')
,('Regulatory', 1, '3111', 'NoncurrentProvisionsForEmployeeBenefits', 'Non-current provisions for employee benefits')
,('Regulatory', 1, '3112', 'OtherLongtermProvisions', 'Other non-current provisions')
,('Regulatory', 1, '31121', 'LongtermWarrantyProvision', 'Non-current warranty provision')
,('Regulatory', 1, '31122', 'LongtermRestructuringProvision', 'Non-current restructuring provision')
,('Regulatory', 1, '31123', 'LongtermLegalProceedingsProvision', 'Non-current legal proceedings provision')
,('Regulatory', 1, '31124', 'NoncurrentRefundsProvision', 'Non-current refunds provision')
,('Regulatory', 1, '31125', 'LongtermOnerousContractsProvision', 'Non-current onerous contracts provision')
,('Regulatory', 1, '31126', 'LongtermProvisionForDecommissioningRestorationAndRehabilitationCosts', 'Non-current provision for decommissioning, restoration and rehabilitation costs')
,('Regulatory', 1, '31127', 'LongtermMiscellaneousOtherProvisions', 'Non-current miscellaneous other provisions')
,('Regulatory', 1, '312', 'NoncurrentPayables', 'Trade and other non-current payables')
,('Regulatory', 1, '3121', 'NoncurrentPayablesToTradeSuppliers', 'Non-current trade payables')
,('Regulatory', 1, '3122', 'NoncurrentPayablesToRelatedParties', 'Non-current payables to related parties')
,('Regulatory', 1, '3123', 'NoncurrentPayablesForPurchaseOfNoncurrentAssets', 'Non-current payables for purchase of non-current assets')
,('Regulatory', 1, '3124', 'AccrualsAndDeferredIncomeClassifiedAsNoncurrent', 'Accruals and deferred income classified as non-current')
,('Regulatory', 1, '31241', 'DeferredIncomeClassifiedAsNoncurrent', 'Deferred income classified as non-current')
,('Regulatory', 1, '312411', 'RentDeferredIncomeClassifiedAsNoncurrent', 'Rent deferred income classified as non-current')
,('Extension', 1, '312412', 'AdvancesFromCustomersClassifiedAsNoncurrent', 'Advances from customers classified as non-current')
,('Regulatory', 1, '31242', 'AccrualsClassifiedAsNoncurrent', 'Accruals classified as non-current')
,('Regulatory', 1, '3125', 'NoncurrentPayablesOnSocialSecurityAndTaxesOtherThanIncomeTax', 'Non-current payables on social security and taxes other than income tax')
,('Regulatory', 1, '31251', 'NoncurrentValueAddedTaxPayables', 'Non-current value added tax payables')
,('Regulatory', 1, '31252', 'NoncurrentExciseTaxPayables', 'Non-current excise tax payables')
,('Regulatory', 1, '3126', 'NoncurrentRetentionPayables', 'Non-current retention payables')
,('Regulatory', 1, '3127', 'OtherNoncurrentPayables', 'Other non-current payables')
,('Regulatory', 1, '313', 'DeferredTaxLiabilities', 'Deferred tax liabilities')
,('Regulatory', 1, '314', 'CurrentTaxLiabilitiesNoncurrent', 'Current tax liabilities, non-current')
,('Regulatory', 1, '315', 'OtherNoncurrentFinancialLiabilities', 'Other non-current financial liabilities')
,('Regulatory', 1, '3151', 'NoncurrentFinancialLiabilitiesAtFairValueThroughProfitOrLoss', 'Non-current financial liabilities at fair value through profit or loss')
,('Regulatory', 1, '31511', 'NoncurrentFinancialLiabilitiesAtFairValueThroughProfitOrLossClassifiedAsHeldForTrading', 'Non-current financial liabilities at fair value through profit or loss, classified as held for trading')
,('Regulatory', 1, '31512', 'NoncurrentFinancialLiabilitiesAtFairValueThroughProfitOrLossDesignatedUponInitialRecognition', 'Non-current financial liabilities at fair value through profit or loss, designated upon initial recognition or subsequently')
,('Regulatory', 1, '3152', 'NoncurrentFinancialLiabilitiesAtAmortisedCost', 'Non-current financial liabilities at amortised cost')
,('Regulatory', 1, '316', 'OtherNoncurrentNonfinancialLiabilities', 'Other non-current non-financial liabilities')
,('Regulatory', 1, '32', 'CurrentLiabilities', 'Current liabilities')
,('Regulatory', 1, '321', 'CurrentLiabilitiesOtherThanLiabilitiesIncludedInDisposalGroupsClassifiedAsHeldForSale', 'Current liabilities other than liabilities included in disposal groups classified as held for sale')
,('Regulatory', 1, '3211', 'CurrentProvisions', 'Current provisions')
,('Regulatory', 1, '32111', 'CurrentProvisionsForEmployeeBenefits', 'Current provisions for employee benefits')
,('Regulatory', 1, '32112', 'OtherShorttermProvisions', 'Other current provisions')
,('Regulatory', 1, '321121', 'ShorttermWarrantyProvision', 'Current warranty provision')
,('Regulatory', 1, '321122', 'ShorttermRestructuringProvision', 'Current restructuring provision')
,('Regulatory', 1, '321123', 'ShorttermLegalProceedingsProvision', 'Current legal proceedings provision')
,('Regulatory', 1, '321124', 'CurrentRefundsProvision', 'Current refunds provision')
,('Regulatory', 1, '321125', 'ShorttermOnerousContractsProvision', 'Current onerous contracts provision')
,('Regulatory', 1, '321126', 'ShorttermProvisionForDecommissioningRestorationAndRehabilitationCosts', 'Current provision for decommissioning, restoration and rehabilitation costs')
,('Regulatory', 1, '321127', 'ShorttermMiscellaneousOtherProvisions', 'Current miscellaneous other provisions')
,('Regulatory', 1, '3212', 'TradeAndOtherCurrentPayables', 'Trade and other current payables')
,('Regulatory', 1, '32121', 'TradeAndOtherCurrentPayablesToTradeSuppliers', 'Current trade payables')
,('Extension', 1, '321211', 'CurrentPayablesToTradeSuppliers', 'Current payables to trade suppliers')
,('Extension', 1, '321212', 'CurrentPayablesToLessors', 'Current payables to lessors')
,('Extension', 1, '321213', 'CurrentPayablesToEmployees', 'Current payables to employees')
,('Regulatory', 1, '32122', 'TradeAndOtherCurrentPayablesToRelatedParties', 'Current payables to related parties')
,('Extension', 1, '321221', 'CurrentPayablesToRelatedTradeSuppliers', 'Current payables to related suppliers')
,('Extension', 1, '321222', 'CurrentPayablesToRelatedLessors', 'Current payables to related lessors')
,('Extension', 1, '321223', 'CurrentPayablesToRelatedEmployees', 'Current payables to related employees')
,('Regulatory', 1, '32123', 'CurrentPayablesForPurchaseOfNoncurrentAssets', 'Current payables for purchase of non-current assets')
,('Regulatory', 1, '32124', 'AccrualsAndDeferredIncomeClassifiedAsCurrent', 'Accruals and deferred income classified as current')
,('Regulatory', 1, '321241', 'DeferredIncomeClassifiedAsCurrent', 'Deferred income classified as current')
,('Regulatory', 1, '3212411', 'RentDeferredIncomeClassifiedAsCurrent', 'Rent deferred income classified as current')
,('Extension', 1, '3212412', 'AdvancesFromCustomersClassifiedAsCurrent', 'Advances from customers classified as current')
,('Regulatory', 1, '321242', 'AccrualsClassifiedAsCurrent', 'Accruals classified as current')
,('Regulatory', 1, '3212421', 'ShorttermEmployeeBenefitsAccruals', 'Short-term employee benefits accruals')
,('Regulatory', 1, '3212422', 'RentAccrualClassifiedAsCurrent', 'Rent accrual classified as current')
,('Extension', 1, '3212423', 'GoodsAndServicesReceivedFromSupplierButNotBilled', 'Goods and services received from supplier but not billed')
,('Regulatory', 1, '32125', 'CurrentPayablesOnSocialSecurityAndTaxesOtherThanIncomeTax', 'Current payables on social security and taxes other than income tax')
,('Regulatory', 1, '321251', 'CurrentValueAddedTaxPayables', 'Current value added tax payables')
,('Regulatory', 1, '321252', 'CurrentExciseTaxPayables', 'Current excise tax payables')
,('Extension', 1, '321253', 'CurrentWithholdingTaxPayable', 'Current withholding tax payable')
,('Extension', 1, '321254', 'CurrentEmployeeIncomeTaxPayable', 'Current employee income tax payable')
,('Extension', 1, '321255', 'CurrentSocialSecurityTaxPayable', 'Current social security tax payable')
,('Extension', 1, '321256', 'CurrentZakatPayable', 'Current social security tax payable')
,('Regulatory', 1, '32126', 'CurrentRetentionPayables', 'Current retention payables')
,('Regulatory', 1, '32127', 'OtherCurrentPayables', 'Other current payables')
,('Extension', 1, '321271', 'GoodsAndServicesBilledToCustomerButNotDelivered', 'Goods and services billed to customer but not delivered')
,('Extension', 1, '321272', 'LeaseOutBilledToLesseeButNotDelivered', 'Lease out billed to lessee but not delivered')
,('Regulatory', 1, '3213', 'CurrentTaxLiabilitiesCurrent', 'Current tax liabilities, current')
,('Regulatory', 1, '3214', 'OtherCurrentFinancialLiabilities', 'Other current financial liabilities')
,('Regulatory', 1, '32141', 'CurrentFinancialLiabilitiesAtFairValueThroughProfitOrLoss', 'Current financial liabilities at fair value through profit or loss')
,('Regulatory', 1, '321411', 'CurrentFinancialLiabilitiesAtFairValueThroughProfitOrLossClassifiedAsHeldForTrading', 'Current financial liabilities at fair value through profit or loss, classified as held for trading')
,('Regulatory', 1, '321412', 'CurrentFinancialLiabilitiesAtFairValueThroughProfitOrLossDesignatedUponInitialRecognition', 'Current financial liabilities at fair value through profit or loss, designated upon initial recognition or subsequently')
,('Regulatory', 1, '32142', 'CurrentFinancialLiabilitiesAtAmortisedCost', 'Current financial liabilities at amortised cost')
,('Regulatory', 1, '3215', 'OtherCurrentNonfinancialLiabilities', 'Other current non-financial liabilities')
,('Regulatory', 1, '322', 'LiabilitiesIncludedInDisposalGroupsClassifiedAsHeldForSale', 'Liabilities included in disposal groups classified as held for sale')

,('Regulatory', 1, '4', 'ProfitLoss', 'Profit (loss)')
,('Regulatory', 1, '41', 'ProfitLossBeforeTax', 'Profit (loss) before tax')
,('Regulatory', 1, '4101', 'ProfitLossFromOperatingActivities', 'Profit (loss) from operating activities')
,('Regulatory', 1, '41011', 'GrossProfit', 'Gross profit')
,('Regulatory', 1, '410111', 'Revenue', 'Revenue')
,('Regulatory', 1, '4101111', 'RevenueFromSaleOfGoods', 'Revenue from sale of goods')
,('Regulatory', 1, '4101112', 'RevenueFromRenderingOfServices', 'Revenue from rendering of services')
,('Regulatory', 1, '4101113', 'RevenueFromConstructionContracts', 'Revenue from construction contracts')
,('Regulatory', 1, '4101114', 'RevenueFromRoyalties', 'Royalty income')
,('Regulatory', 1, '4101115', 'LicenceFeeIncome', 'Licence fee income')
,('Regulatory', 1, '4101116', 'FranchiseFeeIncome', 'Franchise fee income')
,('Regulatory', 1, '4101117', 'RevenueFromInterest', 'Interest income')
,('Regulatory', 1, '4101118', 'RevenueFromDividends', 'Dividend income')
,('Regulatory', 1, '4101119', 'OtherRevenue', 'Other revenue')
,('Regulatory', 1, '410112', 'CostOfSales', 'Cost of sales')
,('Regulatory', 1, '41012', 'OtherIncome', 'Other income')
,('Regulatory', 1, '41013', 'DistributionCosts', 'Distribution costs')
,('Regulatory', 1, '41014', 'AdministrativeExpense', 'Administrative expenses')
,('Regulatory', 1, '41015', 'OtherExpenseByFunction', 'Other expense, by function')
,('Regulatory', 1, '41016', 'OtherGainsLosses', 'Other gains (losses)')
,('Regulatory', 1, '410161', 'GainsLossesOnDisposalsOfNoncurrentAssets', 'Gains (losses) on disposals of non-current assets')
,('Regulatory', 1, '4101611', 'GainsOnDisposalsOfNoncurrentAssets', 'Gains on disposals of non-current assets')
,('Regulatory', 1, '4101612', 'LossesOnDisposalsOfNoncurrentAssets', 'Losses on disposals of non-current assets')
,('Regulatory', 1, '410162', 'GainsLossesOnDisposalsOfPropertyPlantAndEquipment', 'Gains (losses) on disposals of property, plant and equipment')
,('Regulatory', 1, '4101621', 'GainsOnDisposalsOfPropertyPlantAndEquipment', 'Gains on disposals of property, plant and equipment')
,('Regulatory', 1, '4101622', 'LossesOnDisposalsOfPropertyPlantAndEquipment', 'Losses on disposals of property, plant and equipment')
,('Regulatory', 1, '410163', 'GainsLossesOnDisposalsOfInvestmentProperties', 'Gains (losses) on disposals of investment properties')
,('Regulatory', 1, '4101631', 'GainsOnDisposalsOfInvestmentProperties', 'Gains on disposals of investment properties')
,('Regulatory', 1, '4101632', 'LossesOnDisposalsOfInvestmentProperties', 'Losses on disposals of investment properties')
,('Regulatory', 1, '410164', 'GainsLossesOnDisposalsOfInvestments', 'Gains (losses) on disposals of investments')
,('Regulatory', 1, '4101641', 'GainsOnDisposalsOfInvestments', 'Gains on disposals of investments')
,('Regulatory', 1, '4101642', 'LossesOnDisposalsOfInvestments', 'Losses on disposals of investments')
,('Regulatory', 1, '410165', 'GainsLossesOnDisposalsOfOtherNoncurrentAssets', 'Gains (losses) on disposals of other non-current assets')
,('Regulatory', 1, '410166', 'GainLossArisingFromDifferenceBetweenCarryingAmountOfFinancialLiabilityExtinguishedAndConsiderationPaid', 'Gain (loss) arising from difference between carrying amount of financial liability extinguished and consideration paid')
,('Regulatory', 1, '410167', 'GainsLossesOnLitigationSettlements', 'Gains (losses) on litigation settlements')
,('Regulatory', 1, '4101671', 'GainsOnLitigationSettlements', 'Gains on litigation settlements')
,('Regulatory', 1, '4101672', 'LossesOnLitigationSettlements', 'Losses on litigation settlements')
,('Regulatory', 1, '410168', 'GainsLossesOnChangeInFairValueOfDerivatives', 'Gains (losses) on change in fair value of derivatives')
,('Regulatory', 1, '4101681', 'GainsOnChangeInFairValueOfDerivatives', 'Gains on change in fair value of derivatives')
,('Regulatory', 1, '4101682', 'LossesOnChangeInFairValueOfDerivatives', 'Losses on change in fair value of derivatives')
,('Regulatory', 1, '4102', 'DifferenceBetweenCarryingAmountOfDividendsPayableAndCarryingAmountOfNoncashAssetsDistributed', 'Difference between carrying amount of dividends payable and carrying amount of non-cash assets distributed')
,('Regulatory', 1, '4103', 'GainsLossesOnNetMonetaryPosition', 'Gains (losses) on net monetary position')
,('Regulatory', 1, '4104', 'GainLossArisingFromDerecognitionOfFinancialAssetsMeasuredAtAmortisedCost', 'Gain (loss) arising from derecognition of financial assets measured at amortised cost')
,('Regulatory', 1, '41041', 'GainsArisingFromDerecognitionOfFinancialAssetsMeasuredAtAmortisedCost', 'Gains arising from derecognition of financial assets measured at amortised cost')
,('Regulatory', 1, '41042', 'LossesArisingFromDerecognitionOfFinancialAssetsMeasuredAtAmortisedCost', 'Losses arising from derecognition of financial assets measured at amortised cost')
,('Regulatory', 1, '4105', 'FinanceIncome', 'Finance income')
,('Regulatory', 1, '4106', 'FinanceCosts', 'Finance costs')
,('Regulatory', 1, '4107', 'ImpairmentLossImpairmentGainAndReversalOfImpairmentLossDeterminedInAccordanceWithIFRS9', 'Impairment loss (impairment gain and reversal of impairment loss) determined in accordance with IFRS 9')
,('Regulatory', 1, '4108', 'ShareOfProfitLossOfAssociatesAndJointVenturesAccountedForUsingEquityMethod', 'Share of profit (loss) of associates and joint ventures accounted for using equity method')
,('Regulatory', 1, '4109', 'OtherIncomeExpenseFromSubsidiariesJointlyControlledEntitiesAndAssociates', 'Other income (expense) from subsidiaries, jointly controlled entities and associates')
,('Regulatory', 1, '4110', 'GainsLossesArisingFromDifferenceBetweenPreviousCarryingAmountAndFairValueOfFinancialAssetsReclassifiedAsMeasuredAtFairValue', 'Gains (losses) arising from difference between previous amortised cost and fair value of financial assets reclassified out of amortised cost into fair value through profit or loss measurement category')
,('Regulatory', 1, '4111', 'CumulativeGainLossPreviouslyRecognisedInOtherComprehensiveIncomeArisingFromReclassificationOfFinancialAssetsOutOfFairValueThroughOtherComprehensiveIncomeIntoFairValueThroughProfitOrLossMeasurementCategory', 'Cumulative gain (loss) previously recognised in other comprehensive income arising from reclassification of financial assets out of fair value through other comprehensive income into fair value through profit or loss measurement category')
,('Regulatory', 1, '4112', 'HedgingGainsLossesForHedgeOfGroupOfItemsWithOffsettingRiskPositions', 'Hedging gains (losses) for hedge of group of items with offsetting risk positions')
,('Regulatory', 1, '42', 'IncomeTaxExpenseContinuingOperations', 'Tax expense (income), continuing operations')
,('Regulatory', 1, '421', 'CurrentTaxExpenseIncomeAndAdjustmentsForCurrentTaxOfPriorPeriods', 'Current tax expense (income) and adjustments for current tax of prior periods')
,('Regulatory', 1, '422', 'DeferredTaxExpenseIncomeRelatingToOriginationAndReversalOfTemporaryDifferences', 'Deferred tax expense (income) relating to origination and reversal of temporary differences')
,('Regulatory', 1, '423', 'DeferredTaxExpenseIncomeRelatingToTaxRateChangesOrImpositionOfNewTaxes', 'Deferred tax expense (income) relating to tax rate changes or imposition of new taxes')
,('Regulatory', 1, '424', 'TaxBenefitArisingFromPreviouslyUnrecognisedTaxLossTaxCreditOrTemporaryDifferenceOfPriorPeriodUsedToReduceCurrentTaxExpense', 'Tax benefit arising from previously unrecognised tax loss, tax credit or temporary difference of prior period used to reduce current tax expense')
,('Regulatory', 1, '425', 'TaxBenefitArisingFromPreviouslyUnrecognisedTaxLossTaxCreditOrTemporaryDifferenceOfPriorPeriodUsedToReduceDeferredTaxExpense', 'Tax benefit arising from previously unrecognised tax loss, tax credit or temporary difference of prior period used to reduce deferred tax expense')
,('Regulatory', 1, '426', 'DeferredTaxExpenseArisingFromWritedownOrReversalOfWritedownOfDeferredTaxAsset', 'Deferred tax expense arising from write-down or reversal of write-down of deferred tax asset')
,('Regulatory', 1, '427', 'TaxExpenseIncomeRelatingToChangesInAccountingPoliciesAndErrorsIncludedInProfitOrLoss', 'Tax expense (income) relating to changes in accounting policies and errors included in profit or loss')
,('Regulatory', 1, '428', 'AdjustmentsForDeferredTaxOfPriorPeriods', 'Adjustments for deferred tax of prior periods')
,('Regulatory', 1, '429', 'OtherComponentsOfDeferredTaxExpenseIncome', 'Other components of deferred tax expense (income)')
,('Regulatory', 1, '43', 'ProfitLossFromDiscontinuedOperations', 'Profit (loss) from discontinued operations')

,('Regulatory', 1, '5', 'OtherComprehensiveIncome', 'Other comprehensive income')
,('Regulatory', 1, '51', 'OtherComprehensiveIncomeThatWillNotBeReclassifiedToProfitOrLossNetOfTax', 'Other comprehensive income that will not be reclassified to profit or loss, net of tax')
,('Regulatory', 1, '511', 'OtherComprehensiveIncomeNetOfTaxGainsLossesFromInvestmentsInEquityInstruments', 'Other comprehensive income, net of tax, gains (losses) from investments in equity instruments')
,('Regulatory', 1, '512', 'OtherComprehensiveIncomeNetOfTaxGainsLossesOnRevaluation', 'Other comprehensive income, net of tax, gains (losses) on revaluation')
,('Regulatory', 1, '513', 'OtherComprehensiveIncomeNetOfTaxGainsLossesOnRemeasurementsOfDefinedBenefitPlans', 'Other comprehensive income, net of tax, gains (losses) on remeasurements of defined benefit plans')
,('Regulatory', 1, '514', 'OtherComprehensiveIncomeNetOfTaxChangeInFairValueOfFinancialLiabilityAttributableToChangeInCreditRiskOfLiability', 'Other comprehensive income, net of tax, change in fair value of financial liability attributable to change in credit risk of liability')
,('Regulatory', 1, '515', 'OtherComprehensiveIncomeNetOfTaxGainsLossesOnHedgingInstrumentsThatHedgeInvestmentsInEquityInstruments', 'Other comprehensive income, net of tax, gains (losses) on hedging instruments that hedge investments in equity instruments')
,('Regulatory', 1, '516', 'ShareOfOtherComprehensiveIncomeOfAssociatesAndJointVenturesAccountedForUsingEquityMethodThatWillNotBeReclassifiedToProfitOrLossNetOfTax', 'Share of other comprehensive income of associates and joint ventures accounted for using equity method that will not be reclassified to profit or loss, net of tax')
,('Regulatory', 1, '52', 'OtherComprehensiveIncomeThatWillBeReclassifiedToProfitOrLossNetOfTax', 'Other comprehensive income that will be reclassified to profit or loss, net of tax')
,('Regulatory', 1, '521', 'OtherComprehensiveIncomeNetOfTaxExchangeDifferencesOnTranslation', 'Other comprehensive income, net of tax, exchange differences on translation')
,('Regulatory', 1, '5211', 'GainsLossesOnExchangeDifferencesOnTranslationNetOfTax', 'Gains (losses) on exchange differences on translation, net of tax')
,('Regulatory', 1, '5212', 'ReclassificationAdjustmentsOnExchangeDifferencesOnTranslationNetOfTax', 'Reclassification adjustments on exchange differences on translation, net of tax')
,('Regulatory', 1, '522', 'OtherComprehensiveIncomeNetOfTaxCashFlowHedges', 'Other comprehensive income, net of tax, cash flow hedges')
,('Regulatory', 1, '5221', 'GainsLossesOnCashFlowHedgesNetOfTax', 'Gains (losses) on cash flow hedges, net of tax')
,('Regulatory', 1, '5222', 'ReclassificationAdjustmentsOnCashFlowHedgesNetOfTax', 'Reclassification adjustments on cash flow hedges, net of tax')
,('Regulatory', 1, '523', 'OtherComprehensiveIncomeNetOfTaxHedgesOfNetInvestmentsInForeignOperations', 'Other comprehensive income, net of tax, hedges of net investments in foreign operations')
,('Regulatory', 1, '5231', 'GainsLossesOnHedgesOfNetInvestmentsInForeignOperationsNetOfTax', 'Gains (losses) on hedges of net investments in foreign operations, net of tax')
,('Regulatory', 1, '5232', 'ReclassificationAdjustmentsOnHedgesOfNetInvestmentsInForeignOperationsNetOfTax', 'Reclassification adjustments on hedges of net investments in foreign operations, net of tax')
,('Regulatory', 0, '524', 'OtherComprehensiveIncomeNetOfTaxChangeInValueOfTimeValueOfOptions', 'Other comprehensive income, net of tax, change in value of time value of options')
,('Regulatory', 0, '5241', 'GainsLossesOnChangeInValueOfTimeValueOfOptionsNetOfTax', 'Gains (losses) on change in value of time value of options, net of tax')
,('Regulatory', 0, '5242', 'ReclassificationAdjustmentsOnChangeInValueOfTimeValueOfOptionsNetOfTax', 'Reclassification adjustments on change in value of time value of options, net of tax')
,('Regulatory', 0, '525', 'OtherComprehensiveIncomeNetOfTaxChangeInValueOfForwardElementsOfForwardContracts', 'Other comprehensive income, net of tax, change in value of forward elements of forward contracts')
,('Regulatory', 0, '5251', 'GainsLossesOnChangeInValueOfForwardElementsOfForwardContractsNetOfTax', 'Gains (losses) on change in value of forward elements of forward contracts, net of tax')
,('Regulatory', 0, '5252', 'ReclassificationAdjustmentsOnChangeInValueOfForwardElementsOfForwardContractsNetOfTax', 'Reclassification adjustments on change in value of forward elements of forward contracts, net of tax')
,('Regulatory', 0, '526', 'OtherComprehensiveIncomeNetOfTaxChangeInValueOfForeignCurrencyBasisSpreads', 'Other comprehensive income, net of tax, change in value of foreign currency basis spreads')
,('Regulatory', 0, '5261', 'GainsLossesOnChangeInValueOfForeignCurrencyBasisSpreadsNetOfTax', 'Gains (losses) on change in value of foreign currency basis spreads, net of tax')
,('Regulatory', 0, '5262', 'ReclassificationAdjustmentsOnChangeInValueOfForeignCurrencyBasisSpreadsNetOfTax', 'Reclassification adjustments on change in value of foreign currency basis spreads, net of tax')
,('Regulatory', 1, '527', 'OtherComprehensiveIncomeNetOfTaxFinancialAssetsMeasuredAtFairValueThroughOtherComprehensiveIncome', 'Other comprehensive income, net of tax, financial assets measured at fair value through other comprehensive income')
,('Regulatory', 1, '5271', 'GainsLossesOnFinancialAssetsMeasuredAtFairValueThroughOtherComprehensiveIncomeNetOfTax', 'Gains (losses) on financial assets measured at fair value through other comprehensive income, net of tax')
,('Regulatory', 1, '5272', 'ReclassificationAdjustmentsOnFinancialAssetsMeasuredAtFairValueThroughOtherComprehensiveIncomeNetOfTax', 'Reclassification adjustments on financial assets measured at fair value through other comprehensive income, net of tax')
,('Regulatory', 1, '5273', 'AmountsRemovedFromEquityAndAdjustedAgainstFairValueOfFinancialAssetsOnReclassificationOutOfFairValueThroughOtherComprehensiveIncomeMeasurementCategoryNetOfTax', 'Amounts removed from equity and adjusted against fair value of financial assets on reclassification out of fair value through other comprehensive income measurement category, net of tax')
,('Regulatory', 1, '528', 'ShareOfOtherComprehensiveIncomeOfAssociatesAndJointVenturesAccountedForUsingEquityMethodThatWillBeReclassifiedToProfitOrLossNetOfTax', 'Share of other comprehensive income of associates and joint ventures accounted for using equity method that will be reclassified to profit or loss, net of tax');

MERGE dbo.Accounts AS t
USING #Accounts AS s
ON s.Code = t.Code --AND s.tenantId = t.tenantId
WHEN MATCHED AND
(
    t.[Name]					<>	s.[Name]			OR
    t.[Code]					<>	s.[Code]			OR
    t.[IsActive]				<>	s.[IsActive]		OR
    t.[AccountType]				<>	s.[AccountType]		OR
    t.[AccountSpecification]	<>	s.[AccountSpecification]	OR
    t.[IsExtensible]			<>	s.[IsExtensible]
) THEN
UPDATE SET
    t.[Name]					=	s.[Name],  
    t.[Code]					=	s.[Code],
    t.[IsActive]				=	s.[IsActive],
    t.[AccountType]				=	s.[AccountType], 
    t.[AccountSpecification]	=	s.[AccountSpecification],
    t.[IsExtensible]			=	s.[IsExtensible]
WHEN NOT MATCHED BY SOURCE THEN
        DELETE
WHEN NOT MATCHED BY TARGET THEN
        INSERT ([Id], [Name], [Code], [IsActive], [AccountType], [AccountSpecification], [IsExtensible])
        VALUES (s.[Id], s.[Name], s.[Code], s.[IsActive], s.[AccountType], s.[AccountSpecification], s.[IsExtensible]);
--OUTPUT deleted.*, $action, inserted.*; -- Does not work with triggers

DROP TABLE #Accounts;​