INSERT INTO dbo.Notes(NoteType, IsActive, Code, Id, Name) VALUES
('Extension', 1, '11', 'PropertyPlantAndEquipment', 'Property, plant and equipment')
,('Regulatory', 1, '1101', 'AdditionsOtherThanThroughBusinessCombinationsPropertyPlantAndEquipment', 'Additions other than through business combinations, property, plant and equipment')
,('Regulatory', 1, '1102', 'AcquisitionsThroughBusinessCombinationsPropertyPlantAndEquipment', 'Acquisitions through business combinations, property, plant and equipment')
,('Regulatory', 1, '1103', 'IncreaseDecreaseThroughNetExchangeDifferencesPropertyPlantAndEquipment', 'Increase (decrease) through net exchange differences, property, plant and equipment')
,('Regulatory', 1, '1104', 'DepreciationPropertyPlantAndEquipment', 'Depreciation, property, plant and equipment')
,('Regulatory', 1, '1105', 'ImpairmentLossRecognisedInProfitOrLossPropertyPlantAndEquipment', 'Impairment loss recognised in profit or loss, property, plant and equipment')
,('Regulatory', 1, '1106', 'ReversalOfImpairmentLossRecognisedInProfitOrLossPropertyPlantAndEquipment', 'Reversal of impairment loss recognised in profit or loss, property, plant and equipment')
,('Regulatory', 1, '1107', 'RevaluationIncreaseDecreasePropertyPlantAndEquipment', 'Revaluation increase (decrease), property, plant and equipment')
,('Regulatory', 1, '1108', 'ImpairmentLossRecognisedInOtherComprehensiveIncomePropertyPlantAndEquipment', 'Impairment loss recognised in other comprehensive income, property, plant and equipment')
,('Regulatory', 1, '1109', 'ReversalOfImpairmentLossRecognisedInOtherComprehensiveIncomePropertyPlantAndEquipment', 'Reversal of impairment loss recognised in other comprehensive income, property, plant and equipment')
,('Regulatory', 1, '1110', 'IncreaseDecreaseThroughTransfersAndOtherChangesPropertyPlantAndEquipmentAbstract', 'Increase (decrease) through transfers and other changes, property, plant and equipment [abstract]')
,('Regulatory', 1, '11101', 'IncreaseDecreaseThroughTransfersPropertyPlantAndEquipment', 'Increase (decrease) through transfers, property, plant and equipment')
,('Regulatory', 1, '11102', 'IncreaseDecreaseThroughOtherChangesPropertyPlantAndEquipment', 'Increase (decrease) through other changes, property, plant and equipment')
,('Regulatory', 1, '1111', 'DisposalsAndRetirementsPropertyPlantAndEquipment', 'Disposals and retirements, property, plant and equipment')
,('Regulatory', 1, '11111', 'DisposalsPropertyPlantAndEquipment', 'Disposals, property, plant and equipment')
,('Regulatory', 1, '11112', 'RetirementsPropertyPlantAndEquipment', 'Retirements, property, plant and equipment')
,('Regulatory', 1, '1112', 'DecreaseThroughClassifiedAsHeldForSalePropertyPlantAndEquipment', 'Decrease through classified as held for sale, property, plant and equipment')
,('Regulatory', 1, '1113', 'DecreaseThroughLossOfControlOfSubsidiaryPropertyPlantAndEquipment', 'Decrease through loss of control of subsidiary, property, plant and equipment')

,('Extension', 1, '12', 'InvestmentProperty', 'Investment property')
,('Regulatory', 1, '1201', 'AdditionsOtherThanThroughBusinessCombinationsInvestmentProperty', 'Additions other than through business combinations, investment property')
,('Regulatory', 1, '12011', 'AdditionsFromSubsequentExpenditureRecognisedAsAssetInvestmentProperty', 'Additions from subsequent expenditure recognised as asset, investment property')
,('Regulatory', 1, '12012', 'AdditionsFromAcquisitionsInvestmentProperty', 'Additions from acquisitions, investment property')
,('Regulatory', 1, '1202', 'AcquisitionsThroughBusinessCombinationsInvestmentProperty', 'Acquisitions through business combinations, investment property')
,('Regulatory', 1, '1203', 'IncreaseDecreaseThroughNetExchangeDifferencesInvestmentProperty', 'Increase (decrease) through net exchange differences, investment property')
,('Regulatory', 1, '1204', 'DepreciationInvestmentProperty', 'Depreciation, investment property')
,('Regulatory', 1, '1205', 'ImpairmentLossRecognisedInProfitOrLossInvestmentProperty', 'Impairment loss recognised in profit or loss, investment property')
,('Regulatory', 1, '1206', 'ReversalOfImpairmentLossRecognisedInProfitOrLossInvestmentProperty', 'Reversal of impairment loss recognised in profit or loss, investment property')
,('Regulatory', 1, '1207', 'GainsLossesOnFairValueAdjustmentInvestmentProperty', 'Gains (losses) on fair value adjustment, investment property')
,('Regulatory', 1, '1208', 'TransferFromToInventoriesAndOwnerOccupiedPropertyInvestmentProperty', 'Transfer from (to) inventories and owner-occupied property, investment property')
,('Regulatory', 1, '1209', 'TransferFromInvestmentPropertyUnderConstructionOrDevelopmentInvestmentProperty', 'Transfer from investment property under construction or development, investment property')
,('Regulatory', 1, '1210', 'DisposalsInvestmentProperty', 'Disposals, investment property')
,('Regulatory', 1, '1211', 'DecreaseThroughClassifiedAsHeldForSaleInvestmentProperty', 'Decrease through classified as held for sale, investment property')
,('Regulatory', 1, '1212', 'IncreaseDecreaseThroughOtherChangesInvestmentProperty', 'Increase (decrease) through other changes, investment property')

,('Extension', 1, '13', 'Goodwill', 'Goodwill')
,('Regulatory', 1, '131', 'AdditionalRecognitionGoodwill', 'Additional recognition, goodwill')
,('Regulatory', 1, '132', 'SubsequentRecognitionOfDeferredTaxAssetsGoodwill', 'Subsequent recognition of deferred tax assets, goodwill')
,('Regulatory', 1, '133', 'DecreaseThroughClassifiedAsHeldForSaleGoodwill', 'Decrease through classified as held for sale, goodwill')
,('Regulatory', 1, '134', 'GoodwillDerecognisedWithoutHavingPreviouslyBeenIncludedInDisposalGroupClassifiedAsHeldForSale', 'Goodwill derecognised without having previously been included in disposal group classified as held for sale')
,('Regulatory', 1, '135', 'ImpairmentLossRecognisedInProfitOrLossGoodwill', 'Impairment loss recognised in profit or loss, goodwill')
,('Regulatory', 1, '136', 'IncreaseDecreaseThroughNetExchangeDifferencesGoodwill', 'Increase (decrease) through net exchange differences, goodwill')
,('Regulatory', 1, '137', 'IncreaseDecreaseThroughTransfersAndOtherChangesGoodwill', 'Increase (decrease) through other changes, goodwill')

,('Extension', 1, '14', 'IntangibleAssetsOtherThanGoodwill', 'Intangible assets other than goodwill')
,('Regulatory', 1, '1401', 'AdditionsOtherThanThroughBusinessCombinationsIntangibleAssetsOtherThanGoodwill', 'Additions other than through business combinations, intangible assets other than goodwill')
,('Regulatory', 1, '1402', 'AcquisitionsThroughBusinessCombinationsIntangibleAssetsOtherThanGoodwill', 'Acquisitions through business combinations, intangible assets other than goodwill')
,('Regulatory', 1, '1403', 'IncreaseDecreaseThroughNetExchangeDifferencesIntangibleAssetsOtherThanGoodwill', 'Increase (decrease) through net exchange differences, intangible assets other than goodwill')
,('Regulatory', 1, '1404', 'AmortisationIntangibleAssetsOtherThanGoodwill', 'Amortisation, intangible assets other than goodwill')
,('Regulatory', 1, '1405', 'ImpairmentLossRecognisedInProfitOrLossIntangibleAssetsOtherThanGoodwill', 'Impairment loss recognised in profit or loss, intangible assets other than goodwill')
,('Regulatory', 1, '1406', 'ReversalOfImpairmentLossRecognisedInProfitOrLossIntangibleAssetsOtherThanGoodwill', 'Reversal of impairment loss recognised in profit or loss, intangible assets other than goodwill')
,('Regulatory', 1, '1407', 'RevaluationIncreaseDecreaseIntangibleAssetsOtherThanGoodwill', 'Revaluation increase (decrease), intangible assets other than goodwill')
,('Regulatory', 1, '1408', 'ImpairmentLossRecognisedInOtherComprehensiveIncomeIntangibleAssetsOtherThanGoodwill', 'Impairment loss recognised in other comprehensive income, intangible assets other than goodwill')
,('Regulatory', 1, '1409', 'ReversalOfImpairmentLossRecognisedInOtherComprehensiveIncomeIntangibleAssetsOtherThanGoodwill', 'Reversal of impairment loss recognised in other comprehensive income, intangible assets other than goodwill')
,('Regulatory', 1, '1410', 'DecreaseThroughClassifiedAsHeldForSaleIntangibleAssetsOtherThanGoodwill', 'Decrease through classified as held for sale, intangible assets other than goodwill')
,('Regulatory', 1, '1411', 'DecreaseThroughLossOfControlOfSubsidiaryIntangibleAssetsOtherThanGoodwill', 'Decrease through loss of control of subsidiary, intangible assets other than goodwill')
,('Regulatory', 1, '1412', 'DisposalsAndRetirementsIntangibleAssetsOtherThanGoodwill', 'Disposals and retirements, intangible assets other than goodwill')
,('Regulatory', 1, '14121', 'DisposalsIntangibleAssetsOtherThanGoodwill', 'Disposals, intangible assets other than goodwill')
,('Regulatory', 1, '14122', 'RetirementsIntangibleAssetsOtherThanGoodwill', 'Retirements, intangible assets other than goodwill')
,('Regulatory', 1, '1413', 'IncreaseDecreaseThroughTransfersAndOtherChangesIntangibleAssetsOtherThanGoodwill', 'Increase (decrease) through transfers and other changes, intangible assets other than goodwill')
,('Regulatory', 1, '14131', 'IncreaseDecreaseThroughTransfersIntangibleAssetsOtherThanGoodwill', 'Increase (decrease) through transfers, intangible assets other than goodwill')
,('Regulatory', 1, '14132', 'IncreaseDecreaseThroughOtherChangesIntangibleAssetsOtherThanGoodwill', 'Increase (decrease) through other changes, intangible assets other than goodwill')

,('Extension', 1, '15', 'BiologicalAssets', 'Biological assets')
,('Regulatory', 1, '1501', 'AdditionsOtherThanThroughBusinessCombinationsBiologicalAssets', 'Additions other than through business combinations, biological assets')
,('Regulatory', 1, '15011', 'AdditionsFromSubsequentExpenditureRecognisedAsAssetBiologicalAssets', 'Additions from subsequent expenditure recognised as asset, biological assets')
,('Regulatory', 1, '15012', 'AdditionsFromPurchasesBiologicalAssets', 'Additions from purchases, biological assets')
,('Regulatory', 1, '1502', 'AcquisitionsThroughBusinessCombinationsBiologicalAssets', 'Acquisitions through business combinations, biological assets')
,('Regulatory', 1, '1503', 'IncreaseDecreaseThroughNetExchangeDifferencesBiologicalAssets', 'Increase (decrease) through net exchange differences, biological assets')
,('Regulatory', 1, '1504', 'DepreciationBiologicalAssets', 'Depreciation, biological assets')
,('Regulatory', 1, '1505', 'ImpairmentLossRecognisedInProfitOrLossBiologicalAssets', 'Impairment loss recognised in profit or loss, biological assets')
,('Regulatory', 1, '1506', 'ReversalOfImpairmentLossRecognisedInProfitOrLossBiologicalAssets', 'Reversal of impairment loss recognised in profit or loss, biological assets')
,('Regulatory', 1, '1507', 'GainsLossesOnFairValueAdjustmentBiologicalAssets', 'Gains (losses) on fair value adjustment, biological assets')
,('Regulatory', 1, '15071', 'GainsLossesOnFairValueAdjustmentAttributableToPhysicalChangesBiologicalAssets', 'Gains (losses) on fair value adjustment attributable to physical changes, biological assets')
,('Regulatory', 1, '15072', 'GainsLossesOnFairValueAdjustmentAttributableToPriceChangesBiologicalAssets', 'Gains (losses) on fair value adjustment attributable to price changes, biological assets')
,('Regulatory', 1, '1508', 'IncreaseDecreaseThroughTransfersAndOtherChangesBiologicalAssets', 'Increase (decrease) through other changes, biological assets')
,('Regulatory', 1, '1509', 'DisposalsBiologicalAssets', 'Disposals, biological assets')
,('Regulatory', 1, '1510', 'DecreaseDueToHarvestBiologicalAssets', 'Decrease due to harvest, biological assets')
,('Regulatory', 1, '1511', 'DecreaseThroughClassifiedAsHeldForSaleBiologicalAssets', 'Decrease through classified as held for sale, biological assets')

,('Extension', 1, '16', 'CashAndCashEquivalents', 'Cash and cash equivalents')
,('Regulatory', 1, '161', 'IncreaseDecreaseInCashAndCashEquivalentsBeforeEffectOfExchangeRateChanges', 'Increase (decrease) in cash and cash equivalents before effect of exchange rate changes')
,('Regulatory', 1, '1611', 'CashFlowsFromUsedInOperatingActivities', 'Cash flows from (used in) operating activities')
,('Regulatory', 1, '16111', 'CashFlowsFromUsedInOperations', 'Cash flows from (used in) operations')
,('Regulatory', 1, '1611101', 'ReceiptsFromSalesOfGoodsAndRenderingOfServices', 'Receipts from sales of goods and rendering of services')
,('Regulatory', 1, '1611102', 'ReceiptsFromRoyaltiesFeesCommissionsAndOtherRevenue', 'Receipts from royalties, fees, commissions and other revenue')
,('Regulatory', 1, '1611103', 'ReceiptsFromContractsHeldForDealingOrTradingPurpose', 'Receipts from contracts held for dealing or trading purposes')
,('Regulatory', 1, '1611104', 'ReceiptsFromPremiumsAndClaimsAnnuitiesAndOtherPolicyBenefits', 'Receipts from premiums and claims, annuities and other policy benefits')
,('Regulatory', 1, '1611105', 'ReceiptsFromRentsAndSubsequentSalesOfSuchAssets', 'Receipts from rents and subsequent sales of assets held for rental to others and subsequently held for sale')
,('Regulatory', 1, '1611106', 'OtherCashReceiptsFromOperatingActivities', 'Other cash receipts from operating activities')
,('Regulatory', 1, '1611107', 'PaymentsToSuppliersForGoodsAndServices', 'Payments to suppliers for goods and services')
,('Regulatory', 1, '1611108', 'PaymentsFromContractsHeldForDealingOrTradingPurpose', 'Payments from contracts held for dealing or trading purpose')
,('Regulatory', 1, '1611109', 'PaymentsToAndOnBehalfOfEmployees', 'Payments to and on behalf of employees')
,('Regulatory', 1, '1611110', 'PaymentsForPremiumsAndClaimsAnnuitiesAndOtherPolicyBenefits', 'Payments for premiums and claims, annuities and other policy benefits')
,('Regulatory', 1, '1611111', 'PaymentsToManufactureOrAcquireAssetsHeldForRentalToOthersAndSubsequentlyHeldForSale', 'Payments to manufacture or acquire assets held for rental to others and subsequently held for sale')
,('Regulatory', 1, '1611112', 'OtherCashPaymentsFromOperatingActivities', 'Other cash payments from operating activities')
,('Regulatory', 1, '16112', 'DividendsPaidClassifiedAsOperatingActivities', 'Dividends paid, classified as operating activities')
,('Regulatory', 1, '16113', 'DividendsReceivedClassifiedAsOperatingActivities', 'Dividends received, classified as operating activities')
,('Regulatory', 1, '16114', 'InterestPaidClassifiedAsOperatingActivities', 'Interest paid, classified as operating activities')
,('Regulatory', 1, '16115', 'InterestReceivedClassifiedAsOperatingActivities', 'Interest received, classified as operating activities')
,('Regulatory', 1, '16116', 'IncomeTaxesPaidRefundClassifiedAsOperatingActivities', 'Income taxes paid (refund), classified as operating activities')
,('Regulatory', 1, '16117', 'OtherInflowsOutflowsOfCashClassifiedAsOperatingActivities', 'Other inflows (outflows) of cash, classified as operating activities')
,('Regulatory', 1, '1612', 'CashFlowsFromUsedInInvestingActivities', 'Cash flows from (used in) investing activities')
,('Regulatory', 1, '161201', 'CashFlowsFromLosingControlOfSubsidiariesOrOtherBusinessesClassifiedAsInvestingActivities', 'Cash flows from losing control of subsidiaries or other businesses, classified as investing activities')
,('Regulatory', 1, '161202', 'CashFlowsUsedInObtainingControlOfSubsidiariesOrOtherBusinessesClassifiedAsInvestingActivities', 'Cash flows used in obtaining control of subsidiaries or other businesses, classified as investing activities')
,('Regulatory', 1, '161203', 'OtherCashReceiptsFromSalesOfEquityOrDebtInstrumentsOfOtherEntitiesClassifiedAsInvestingActivities', 'Other cash receipts from sales of equity or debt instruments of other entities, classified as investing activities')
,('Regulatory', 1, '161204', 'OtherCashPaymentsToAcquireEquityOrDebtInstrumentsOfOtherEntitiesClassifiedAsInvestingActivities', 'Other cash payments to acquire equity or debt instruments of other entities, classified as investing activities')
,('Regulatory', 1, '161205', 'OtherCashReceiptsFromSalesOfInterestsInJointVenturesClassifiedAsInvestingActivities', 'Other cash receipts from sales of interests in joint ventures, classified as investing activities')
,('Regulatory', 1, '161206', 'OtherCashPaymentsToAcquireInterestsInJointVenturesClassifiedAsInvestingActivities', 'Other cash payments to acquire interests in joint ventures, classified as investing activities')
,('Regulatory', 1, '161207', 'ProceedsFromSalesOfPropertyPlantAndEquipmentClassifiedAsInvestingActivities', 'Proceeds from sales of property, plant and equipment, classified as investing activities')
,('Regulatory', 1, '161208', 'PurchaseOfPropertyPlantAndEquipmentClassifiedAsInvestingActivities', 'Purchase of property, plant and equipment, classified as investing activities')
,('Regulatory', 1, '161209', 'ProceedsFromSalesOfIntangibleAssetsClassifiedAsInvestingActivities', 'Proceeds from sales of intangible assets, classified as investing activities')
,('Regulatory', 1, '161210', 'PurchaseOfIntangibleAssetsClassifiedAsInvestingActivities', 'Purchase of intangible assets, classified as investing activities')
,('Regulatory', 1, '161211', 'ProceedsFromOtherLongtermAssetsClassifiedAsInvestingActivities', 'Proceeds from sales of other long-term assets, classified as investing activities')
,('Regulatory', 1, '161212', 'PurchaseOfOtherLongtermAssetsClassifiedAsInvestingActivities', 'Purchase of other long-term assets, classified as investing activities')
,('Regulatory', 1, '161213', 'ProceedsFromGovernmentGrantsClassifiedAsInvestingActivities', 'Proceeds from government grants, classified as investing activities')
,('Regulatory', 1, '161214', 'CashAdvancesAndLoansMadeToOtherPartiesClassifiedAsInvestingActivities', 'Cash advances and loans made to other parties, classified as investing activities')
,('Regulatory', 1, '161215', 'CashReceiptsFromRepaymentOfAdvancesAndLoansMadeToOtherPartiesClassifiedAsInvestingActivities', 'Cash receipts from repayment of advances and loans made to other parties, classified as investing activities')
,('Regulatory', 1, '161216', 'CashPaymentsForFutureContractsForwardContractsOptionContractsAndSwapContractsClassifiedAsInvestingActivities', 'Cash payments for futures contracts, forward contracts, option contracts and swap contracts, classified as investing activities')
,('Regulatory', 1, '161217', 'CashReceiptsFromFutureContractsForwardContractsOptionContractsAndSwapContractsClassifiedAsInvestingActivities', 'Cash receipts from futures contracts, forward contracts, option contracts and swap contracts, classified as investing activities')
,('Regulatory', 1, '161218', 'DividendsReceivedClassifiedAsInvestingActivities', 'Dividends received, classified as investing activities')
,('Regulatory', 1, '161219', 'InterestPaidClassifiedAsInvestingActivities', 'Interest paid, classified as investing activities')
,('Regulatory', 1, '161220', 'InterestReceivedClassifiedAsInvestingActivities', 'Interest received, classified as investing activities')
,('Regulatory', 1, '161221', 'IncomeTaxesPaidRefundClassifiedAsInvestingActivities', 'Income taxes paid (refund), classified as investing activities')
,('Regulatory', 1, '161222', 'OtherInflowsOutflowsOfCashClassifiedAsInvestingActivities', 'Other inflows (outflows) of cash, classified as investing activities')
,('Regulatory', 1, '1613', 'CashFlowsFromUsedInFinancingActivities', 'Cash flows from (used in) financing activities')
,('Regulatory', 1, '161301', 'ProceedsFromChangesInOwnershipInterestsInSubsidiaries', 'Proceeds from changes in ownership interests in subsidiaries that do not result in loss of control')
,('Regulatory', 1, '161302', 'PaymentsFromChangesInOwnershipInterestsInSubsidiaries', 'Payments from changes in ownership interests in subsidiaries that do not result in loss of control')
,('Regulatory', 1, '161303', 'ProceedsFromIssuingShares', 'Proceeds from issuing shares')
,('Regulatory', 1, '161304', 'ProceedsFromIssuingOtherEquityInstruments', 'Proceeds from issuing other equity instruments')
,('Regulatory', 1, '161305', 'PaymentsToAcquireOrRedeemEntitysShares', 'Payments to acquire or redeem entity''s shares')
,('Regulatory', 1, '161306', 'PaymentsOfOtherEquityInstruments', 'Payments of other equity instruments')
,('Regulatory', 1, '161307', 'ProceedsFromBorrowingsClassifiedAsFinancingActivities', 'Proceeds from borrowings, classified as financing activities')
,('Regulatory', 1, '161308', 'RepaymentsOfBorrowingsClassifiedAsFinancingActivities', 'Repayments of borrowings, classified as financing activities')
,('Regulatory', 1, '161309', 'PaymentsOfLeaseLiabilitiesClassifiedAsFinancingActivities', 'Payments of lease liabilities, classified as financing activities')
,('Regulatory', 1, '161310', 'ProceedsFromGovernmentGrantsClassifiedAsFinancingActivities', 'Proceeds from government grants, classified as financing activities')
,('Regulatory', 1, '161311', 'DividendsPaidClassifiedAsFinancingActivities', 'Dividends paid, classified as financing activities')
,('Regulatory', 1, '161312', 'InterestPaidClassifiedAsFinancingActivities', 'Interest paid, classified as financing activities')
,('Regulatory', 1, '161313', 'IncomeTaxesPaidRefundClassifiedAsFinancingActivities', 'Income taxes paid (refund), classified as financing activities')
,('Regulatory', 1, '161314', 'OtherInflowsOutflowsOfCashClassifiedAsFinancingActivities', 'Other inflows (outflows) of cash, classified as financing activities')
,('Extension', 1, '1614', 'InternalCashTransfer', 'Internal cash transfer')
,('Regulatory', 1, '162', 'EffectOfExchangeRateChangesOnCashAndCashEquivalents', 'Effect of exchange rate changes on cash and cash equivalents')

,('Extension', 1, '2', 'Equity', 'Equity')
,('Regulatory', 1, '201', 'ComprehensiveIncome', 'Comprehensive income')
,('Regulatory', 1, '2011', 'ProfitLoss', 'Profit (loss)')
,('Regulatory', 1, '2012', 'OtherComprehensiveIncome', 'Other comprehensive income')
,('Regulatory', 1, '202', 'IssueOfEquity', 'Issue of equity')
,('Regulatory', 1, '203', 'DividendsPaid', 'Dividends recognised as distributions to owners')
,('Regulatory', 1, '204', 'IncreaseDecreaseThroughOtherContributionsByOwners', 'Increase through other contributions by owners, equity')
,('Regulatory', 1, '205', 'IncreaseDecreaseThroughOtherDistributionsToOwners', 'Decrease through other distributions to owners, equity')
,('Regulatory', 1, '206', 'IncreaseDecreaseThroughTransfersAndOtherChangesEquity', 'Increase (decrease) through other changes, equity')
,('Regulatory', 1, '207', 'IncreaseDecreaseThroughTreasuryShareTransactions', 'Increase (decrease) through treasury share transactions, equity')
,('Regulatory', 1, '208', 'IncreaseDecreaseThroughChangesInOwnershipInterestsInSubsidiariesThatDoNotResultInLossOfControl', 'Increase (decrease) through changes in ownership interests in subsidiaries that do not result in loss of control, equity')
,('Regulatory', 1, '209', 'IncreaseDecreaseThroughSharebasedPaymentTransactions', 'Increase (decrease) through share-based payment transactions, equity')
,('Regulatory', 1, '210', 'AmountRemovedFromReserveOfCashFlowHedgesAndIncludedInInitialCostOrOtherCarryingAmountOfNonfinancialAssetLiabilityOrFirmCommitmentForWhichFairValueHedgeAccountingIsApplied', 'Amount removed from reserve of cash flow hedges and included in initial cost or other carrying amount of non-financial asset (liability) or firm commitment for which fair value hedge accounting is applied')
,('Regulatory', 1, '211', 'AmountRemovedFromReserveOfChangeInValueOfTimeValueOfOptionsAndIncludedInInitialCostOrOtherCarryingAmountOfNonfinancialAssetLiabilityOrFirmCommitmentForWhichFairValueHedgeAccountingIsApplied', 'Amount removed from reserve of change in value of time value of options and included in initial cost or other carrying amount of non-financial asset (liability) or firm commitment for which fair value hedge accounting is applied')
,('Regulatory', 1, '212', 'AmountRemovedFromReserveOfChangeInValueOfForwardElementsOfForwardContractsAndIncludedInInitialCostOrOtherCarryingAmountOfNonfinancialAssetLiabilityOrFirmCommitmentForWhichFairValueHedgeAccountingIsApplied', 'Amount removed from reserve of change in value of forward elements of forward contracts and included in initial cost or other carrying amount of non-financial asset (liability) or firm commitment for which fair value hedge accounting is applied')
,('Regulatory', 1, '213', 'AmountRemovedFromReserveOfChangeInValueOfForeignCurrencyBasisSpreadsAndIncludedInInitialCostOrOtherCarryingAmountOfNonfinancialAssetLiabilityOrFirmCommitmentForWhichFairValueHedgeAccountingIsApplied', 'Amount removed from reserve of change in value of foreign currency basis spreads and included in initial cost or other carrying amount of non-financial asset (liability) or firm commitment for which fair value hedge accounting is applied')

,('Extension', 1, '3', 'OtherLongtermProvisions', 'Other non-current provisions')
,('Regulatory', 1, '31', 'AdditionalProvisionsOtherProvisions', 'Additional provisions, other provisions')
,('Regulatory', 1, '311', 'NewProvisionsOtherProvisions', 'New provisions, other provisions')
,('Regulatory', 1, '312', 'IncreaseDecreaseInExistingProvisionsOtherProvisions', 'Increase in existing provisions, other provisions')
,('Regulatory', 1, '32', 'AcquisitionsThroughBusinessCombinationsOtherProvisions', 'Acquisitions through business combinations, other provisions')
,('Regulatory', 1, '33', 'ProvisionUsedOtherProvisions', 'Provision used, other provisions')
,('Regulatory', 1, '34', 'UnusedProvisionReversedOtherProvisions', 'Unused provision reversed, other provisions')
,('Regulatory', 1, '35', 'IncreaseDecreaseThroughTimeValueOfMoneyAdjustmentOtherProvisions', 'Increase through adjustments arising from passage of time, other provisions')
,('Regulatory', 1, '36', 'IncreaseDecreaseThroughChangeInDiscountRateOtherProvisions', 'Increase (decrease) through change in discount rate, other provisions')
,('Regulatory', 1, '37', 'IncreaseDecreaseThroughNetExchangeDifferencesOtherProvisions', 'Increase (decrease) through net exchange differences, other provisions')
,('Regulatory', 1, '38', 'DecreaseThroughLossOfControlOfSubsidiaryOtherProvisions', 'Decrease through loss of control of subsidiary, other provisions')
,('Regulatory', 1, '39', 'IncreaseDecreaseThroughTransfersAndOtherChangesOtherProvisions', 'Increase (decrease) through transfers and other changes, other provisions')

,('Extension', 1, '4', 'ExpenseByNature', 'Expenses, by nature')
,('Regulatory', 1, '41', 'RawMaterialsAndConsumablesUsed', 'Raw materials and consumables used')
,('Regulatory', 1, '42', 'CostOfMerchandiseSold', 'Cost of merchandise sold')
,('Regulatory', 1, '43', 'ServicesExpense', 'Services expense')
,('Regulatory', 1, '4301', 'InsuranceExpense', 'Insurance expense')
,('Regulatory', 1, '4302', 'ProfessionalFeesExpense', 'Professional fees expense')
,('Regulatory', 1, '4303', 'TransportationExpense', 'Transportation expense')
,('Regulatory', 1, '4304', 'BankAndSimilarCharges', 'Bank and similar charges')
,('Regulatory', 1, '4305', 'EnergyTransmissionCharges', 'Energy transmission charges')
,('Regulatory', 1, '4306', 'TravelExpense', 'Travel expense')
,('Regulatory', 1, '4307', 'CommunicationExpense', 'Communication expense')
,('Regulatory', 1, '4308', 'UtilitiesExpense', 'Utilities expense')
,('Regulatory', 1, '4309', 'AdvertisingExpense', 'Advertising expense')
,('Regulatory', 1, '4310', 'OfficeSpaceExpense', 'Office space expense')
,('Regulatory', 1, '44', 'EmployeeBenefitsExpense', 'Employee benefits expense')
,('Regulatory', 1, '441', 'ShorttermEmployeeBenefitsExpense', 'Short-term employee benefits expense')
,('Regulatory', 1, '4411', 'WagesAndSalaries', 'Wages and salaries')
,('Regulatory', 1, '4412', 'SocialSecurityContributions', 'Social security contributions')
,('Regulatory', 1, '4413', 'OtherShorttermEmployeeBenefits', 'Other short-term employee benefits')
,('Regulatory', 1, '442', 'PostemploymentBenefitExpenseDefinedContributionPlans', 'Post-employment benefit expense, defined contribution plans')
,('Regulatory', 1, '443', 'PostemploymentBenefitExpenseDefinedBenefitPlans', 'Post-employment benefit expense, defined benefit plans')
,('Regulatory', 1, '444', 'TerminationBenefitsExpense', 'Termination benefits expense')
,('Regulatory', 1, '445', 'OtherLongtermBenefits', 'Other long-term employee benefits')
,('Regulatory', 1, '446', 'OtherEmployeeExpense', 'Other employee expense')
,('Regulatory', 1, '45', 'DepreciationAmortisationAndImpairmentLossReversalOfImpairmentLossRecognisedInProfitOrLoss', 'Depreciation, amortisation and impairment loss (reversal of impairment loss) recognised in profit or loss')
,('Regulatory', 1, '451', 'DepreciationAndAmortisationExpense', 'Depreciation and amortisation expense')
,('Regulatory', 1, '4511', 'DepreciationExpense', 'Depreciation expense')
,('Regulatory', 1, '4512', 'AmortisationExpense', 'Amortisation expense')
,('Regulatory', 1, '452', 'ImpairmentLossReversalOfImpairmentLossRecognisedInProfitOrLoss', 'Impairment loss (reversal of impairment loss) recognised in profit or loss')
,('Regulatory', 1, '4521', 'WritedownsReversalsOfInventories', 'Write-downs (reversals of write-downs) of inventories')
,('Regulatory', 1, '45211', 'InventoryWritedown2011', 'Inventory write-down')
,('Regulatory', 1, '45212', 'ReversalOfInventoryWritedown', 'Reversal of inventory write-down')
,('Regulatory', 1, '4522', 'WritedownsReversalsOfPropertyPlantAndEquipment', 'Write-downs (reversals of write-downs) of property, plant and equipment')


,('Regulatory', 1, '4523', 'ImpairmentLossReversalOfImpairmentLossRecognisedInProfitOrLossTradeReceivables', 'Impairment loss (reversal of impairment loss) recognised in profit or loss, trade receivables')
,('Regulatory', 1, '45231', 'ImpairmentLossRecognisedInProfitOrLossTradeReceivables', 'Impairment loss recognised in profit or loss, trade receivables')
,('Regulatory', 1, '45232', 'ReversalOfImpairmentLossRecognisedInProfitOrLossTradeReceivables', 'Reversal of impairment loss recognised in profit or loss, trade receivables')
,('Regulatory', 1, '4524', 'ImpairmentLossReversalOfImpairmentLossRecognisedInProfitOrLossLoansAndAdvances', 'Impairment loss (reversal of impairment loss) recognised in profit or loss, loans and advances')
,('Regulatory', 1, '45241', 'ImpairmentLossRecognisedInProfitOrLossLoansAndAdvances', 'Impairment loss recognised in profit or loss, loans and advances')
,('Regulatory', 1, '45242', 'ReversalOfImpairmentLossRecognisedInProfitOrLossLoansAndAdvances', 'Reversal of impairment loss recognised in profit or loss, loans and advances')
,('Regulatory', 1, '46', 'TaxExpenseOtherThanIncomeTaxExpense', 'Tax expense other than income tax expense')
,('Regulatory', 1, '47', 'OtherExpenseByNature', 'Other expenses, by nature');